#!/usr/bin/env bash
# Extract the production Cache-Control token/delta helpers verbatim.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_http_cache_turbo_module.c"
OUT="$DIR/generated_cc_delta.inc"

extract_function() {
	local symbol="$1" return_type="$2"
	awk -v symbol="$symbol" -v return_type="$return_type" '
    capture { print; if ($0 == "}") { exit }; next }
    index($0, symbol "(") == 1 {
        capture = 1
        print "static " return_type
        print
        next
    }
    ' "$SRC"
}

token_body="$(extract_function ngx_http_cache_turbo_cc_token 'u_char *')"
has_body="$(extract_function ngx_http_cache_turbo_cc_has ngx_int_t)"
parse_body="$(extract_function ngx_http_cache_turbo_cc_parse_delta time_t)"
delta_body="$(extract_function ngx_http_cache_turbo_cc_delta time_t)"

if [ -z "$token_body" ] || [ -z "$has_body" ] ||
	[ -z "$parse_body" ] || [ -z "$delta_body" ]; then
	echo "✗ failed to extract Cache-Control helpers from $SRC" >&2
	rm -f "$OUT"
	exit 1
fi

{
	echo "/* generated by ci/tests/unit/extract_cc_delta.sh — do not edit */"
	printf '%s\n\n' "$token_body"
	printf '%s\n\n' "$has_body"
	printf '%s\n\n' "$parse_body"
	printf '%s\n' "$delta_body"
} >"$OUT"

echo "✓ extracted Cache-Control token/delta helpers → $(basename "$OUT")"
