#!/usr/bin/env bash
#
# Slice the verbatim body of the cache-turbo content-digest functions into
# generated_digest.inc:
#
#   ngx_http_cache_turbo_digest_init      per-worker EVP_MD_CTX/EVP_MD setup
#                                         (C0: adds the cached EVP_MD_fetch())
#   ngx_http_cache_turbo_digest_update    streaming update
#   ngx_http_cache_turbo_digest_final     finalise into the 32-byte slot
#   ngx_http_cache_turbo_digest           one-shot convenience wrapper
#
# all from ../../../src/ngx_http_cache_turbo_blob.c.
#
# C0 (PLAN-hitpath-2026-08-23.md) replaced the per-call EVP_sha256() (a legacy
# EVP_ORIG_GLOBAL handle that forces an implicit OpenSSL 3.x provider FETCH on
# every EVP_DigestInit_ex()) with a worker-persistent EVP_MD* fetched once via
# EVP_MD_fetch(NULL, "SHA2-256", NULL). The digest IS the cache key (including
# the L2 wire key shared across nodes), so the fetched-path output MUST be
# byte-identical to the EVP_sha256() path for the same input -- that is the
# whole risk of this chunk. test_digest.c pins both paths against a SHA-256
# vector computed independently (`sha256sum`, not this code) and asserts they
# agree, against the REAL functions sliced out of blob.c by this script, not a
# mirror of them.
#
# If the functions can no longer be found we fail loudly rather than silently
# test nothing. Same contract as extract_key_fold.sh / extract_variant_hash.sh.
#
# Usage: ci/tests/unit/extract_digest.sh   (no args; called from run.sh)
# Output: ci/tests/unit/generated_digest.inc  (overwritten; removed on failure)

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_http_cache_turbo_blob.c"
OUT="$DIR/generated_digest.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

{
    echo "/* generated by ci/tests/unit/extract_digest.sh — do not edit */"
    echo ""
} > "$OUT"

# Same extractor shape as extract_key_fold.sh's extract_fn: capture from the
# line immediately before "name(" (the return-type line, e.g. "void" or
# "ngx_int_t" on its own line, nginx style) through the function's own
# closing brace at column 0. A nested brace inside the body (if/else, etc.)
# is always indented in this file's style, so it never matches "}" alone.
extract_fn() {
    local name="$1" src="$2"
    awk -v name="$name" '
        capture { print; if ($0 == "}") { capture = 0; print ""; exit }; next }
        index($0, name "(") == 1 { capture = 1; printf "%s", buf; print; buf = ""; next }
        { buf = $0 ORS }
    ' "$src"
}

for fn in \
    ngx_http_cache_turbo_digest_init \
    ngx_http_cache_turbo_digest_update \
    ngx_http_cache_turbo_digest_final \
    ngx_http_cache_turbo_digest
do
    body="$(extract_fn "$fn" "$SRC")"
    if [ -z "$body" ]; then
        echo "✗ failed to extract $fn from $SRC" >&2
        echo "  (source layout changed? update extract_digest.sh)" >&2
        rm -f "$OUT"
        exit 1
    fi
    printf '%s\n' "$body" >> "$OUT"
done

# --- guard: digest_init must still call EVP_MD_fetch with a fixed algorithm
# string, cached in the worker-persistent global -- a regression back to a
# per-call fetch (or dropping the cache) would still pass a byte-identity
# test (same bytes, quadratic hashtable lookups again), so guard the shape
# too, same convention as extract_key_fold.sh's ngx_pnalloc-count guard.
if ! grep -q 'EVP_MD_fetch' "$OUT"; then
    echo "✗ generated_digest.inc no longer calls EVP_MD_fetch (C0 regressed?)" >&2
    rm -f "$OUT"
    exit 1
fi
if [ "$(grep -c 'EVP_MD_fetch(' "$OUT")" -ne 1 ]; then
    echo "✗ generated_digest.inc calls EVP_MD_fetch more than once" >&2
    echo "  (C0 requires ONE fetch per worker, not one per digest)" >&2
    rm -f "$OUT"
    exit 1
fi

echo "✓ extracted digest functions → $(basename "$OUT")"
