#!/usr/bin/env bash
#
# Slice the VERBATIM open-coded token sort out of
# ../../../src/ngx_http_cache_turbo_module.c into generated_tok_sort.inc, and
# the comparator ngx_http_cache_turbo_tok_cmp out of
# ../../../src/ngx_http_cache_turbo_vary.c.
#
# R3-2 replaced ngx_sort() -- which ngx_alloc()/ngx_free()s a 16-byte scratch
# slot per call, a malloc/free pair per request on the cache-key path -- with an
# open-coded insertion sort using a stack temp. The order it produces IS the
# cache key, so it must be BYTE-IDENTICAL to ngx_sort()'s for every input: any
# divergence silently splits or merges cache entries.
#
# test_tok_sort.c compiles this slice against a verbatim replica of nginx's own
# ngx_sort() (src/core/ngx_string.c) and requires the two to agree element-for-
# element on randomized and adversarial inputs. Slicing rather than mirroring is
# what makes that a real oracle: the test exercises PRODUCTION's loop, so it
# cannot drift into testing a copy that stayed correct while src/ changed.
#
# If the loop can no longer be found we fail loudly rather than silently test
# nothing. Same contract as extract_key_fold.sh / extract_variant_hash.sh.
#
# Usage: ci/tests/unit/extract_tok_sort.sh   (no args; called from run.sh)
# Output: ci/tests/unit/generated_tok_sort.inc  (overwritten; removed on failure)

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_http_cache_turbo_module.c"
SRC_VARY="$DIR/../../../src/ngx_http_cache_turbo_vary.c"
OUT="$DIR/generated_tok_sort.inc"

for f in "$SRC" "$SRC_VARY"; do
    if [ ! -f "$f" ]; then
        echo "✗ cannot find $f" >&2
        exit 1
    fi
done

{
    echo "/* generated by ci/tests/unit/extract_tok_sort.sh — do not edit */"
    echo ""
} > "$OUT"

# --- the comparator, whole function, from vary.c ---------------------------
cmp_body="$(awk '
    capture { print; if ($0 == "}") { exit }; next }
    index($0, "ngx_http_cache_turbo_tok_cmp(") == 1 { capture = 1; print "static ngx_int_t"; print; next }
' "$SRC_VARY")"

if [ -z "$cmp_body" ]; then
    echo "✗ failed to extract ngx_http_cache_turbo_tok_cmp from $SRC_VARY" >&2
    echo "  (source layout changed? update extract_tok_sort.sh)" >&2
    rm -f "$OUT"
    exit 1
fi
printf '%s\n\n' "$cmp_body" >> "$OUT"

# --- the sort loop itself, wrapped into a callable function ----------------
# Anchored on the R3-2 marker comment so a reshuffle of the surrounding
# function cannot silently slice the wrong loop.
loop="$(awk '
    /R3-2: open-coded rather than ngx_sort/ { seen = 1 }
    seen && /^    for \(i = 1; i < kept; i\+\+\) \{$/ { capture = 1 }
    capture { print; if ($0 == "    }") { exit } }
' "$SRC")"

if [ -z "$loop" ]; then
    echo "✗ failed to extract the R3-2 open-coded sort loop from $SRC" >&2
    echo "  (source layout changed, or the loop reverted to ngx_sort?)" >&2
    rm -f "$OUT"
    exit 1
fi

{
    echo "static void"
    echo "ct_tok_sort(ngx_str_t *toks, ngx_uint_t kept)"
    echo "{"
    echo "    ngx_uint_t  i;"
    echo ""
    printf '%s\n' "$loop"
    echo "}"
} >> "$OUT"

# --- guard: the sliced loop must NOT allocate ------------------------------
# The entire point of R3-2 is that the scratch temp is on the STACK. A
# regression that reintroduced ngx_sort(), ngx_alloc() or a pool allocation
# would still sort correctly -- byte-identity would stay green while the
# malloc/free pair came back -- so guard the shape here too.
if grep -qE 'ngx_sort|ngx_alloc|ngx_palloc|ngx_pnalloc|malloc' "$OUT"; then
    echo "✗ generated_tok_sort.inc allocates -- R3-2 requires a stack temp" >&2
    rm -f "$OUT"
    exit 1
fi

echo "✓ extracted token sort + comparator → $(basename "$OUT")"
