#!/usr/bin/env bash
#
# Slice the verbatim bodies of the cache-turbo Vary-key digests out of the
# shipped ../../src/ngx_http_cache_turbo_vary.c into generated_variant.inc:
#
#   ngx_http_cache_turbo_variant_hash()       variant cache key
#   ngx_http_cache_turbo_marker_hash()        marker cache key
#   ngx_http_cache_turbo_variant_index_name() Redis enumeration tag
#
# The test that consumes this (test_variant_gen.c) calls the REAL function with
# bits == 0, which is the only reason this works without an ngx_http_request_t:
# variant_hash dereferences `r` ONLY inside its four `if (bits & ...)` branches
# (ae_class / device_class / lang_class / req_header). With no vary axes set it
# touches nothing but `base`, `gen` and the digest, so the gen-fold behaviour is
# reachable from a unit test while still being PRODUCTION code, not a mirror.
#
# The digest itself is NOT sliced -- it is EVP/OpenSSL in production and the
# test links a small real-MD5 stand-in via ngx_shim_variant.h. What matters for
# the AUD-GEN1 claim is whether two gen values produce the same digest INPUT;
# any collision-free hash over that input answers it identically.
#
# If the function can no longer be found we fail loudly rather than silently
# test nothing. Same contract as ci/fuzz/extract_blob.sh.
#
# Usage: ci/tests/unit/extract_variant_hash.sh   (no args; called from run.sh)
# Output: ci/tests/unit/generated_variant.inc  (overwritten; removed on failure)

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_http_cache_turbo_vary.c"
OUT="$DIR/generated_variant.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

{
    echo "/* generated by ci/tests/unit/extract_variant_hash.sh — do not edit */"
    echo ""
} > "$OUT"

# --- slice the function body.
# nginx style: the return type sits alone on one line, the name+params line
# follows, and the body closes on a bare `}` in column 0. variant_hash is
# non-static in vary.c (module.c calls it cross-TU), so the return-type line
# has no `static` prefix -- match either form.
awk '
    /^static / || /^(void|ngx_int_t|size_t)$/ { pending = 1; buf = $0 ORS; next }
    pending && /^ngx_http_cache_turbo_(variant_hash|marker_hash|variant_index_name)\(/ {
        capture = 1; pending = 0; printf "%s", buf; print; next
    }
    pending { pending = 0; buf = "" }
    capture {
        print
        if ($0 == "}") { capture = 0; print "" }
    }
' "$SRC" >> "$OUT"

if ! grep -qF 'ngx_http_cache_turbo_variant_hash(' "$OUT"; then
    echo "✗ failed to extract ngx_http_cache_turbo_variant_hash from $SRC" >&2
    echo "  (source layout changed? update extract_variant_hash.sh)" >&2
    rm -f "$OUT"
    exit 1
fi
for fn in ngx_http_cache_turbo_marker_hash ngx_http_cache_turbo_variant_index_name; do
    if ! grep -qF "$fn(" "$OUT"; then
        echo "✗ failed to extract $fn from $SRC" >&2
        rm -f "$OUT"
        exit 1
    fi
done

# --- guard: the gen fold must still be REACHED for every gen value.
# AUD-GEN1 was closed by folding the generation unconditionally; a
# reintroduced `gen > 0` / `gen != 0` guard around the fold puts the 256th
# purge back onto the never-purged keyspace. The test asserts the observable
# consequence, but this catches the specific regression at build time with a
# message that names it.
fold="$(sed -n '/PURGE generation/,/^    }/p' "$OUT")"
if printf '%s' "$fold" | grep -qE 'if[[:space:]]*\([[:space:]]*gen[[:space:]]*[!>]'; then
    echo "✗ the PURGE-generation fold is guarded on gen again (AUD-GEN1)" >&2
    echo "  folding must be UNCONDITIONAL; see the comment at the fold site" >&2
    rm -f "$OUT"
    exit 1
fi

if ! printf '%s' "$fold" | grep -qF '"gen="'; then
    echo "✗ the PURGE-generation fold no longer emits its \"gen=\" tag" >&2
    echo "  (renamed or removed? update extract_variant_hash.sh and the test)" >&2
    rm -f "$OUT"
    exit 1
fi

# Falsifiable wire-normalization control. Remove only the production mask;
# direct gen=256 must then diverge from the persisted/read-back gen=0 key.
if [ "${CTRL_VARIANT_NO_GEN_NORMALIZE:-0}" = 1 ]; then
    normalize_line='    gen &= 0xff;'
    if [ "$(grep -cxF "$normalize_line" "$OUT")" -ne 1 ]; then
        echo "✗ generation-normalization mutation could not find its line" >&2
        rm -f "$OUT"
        exit 1
    fi
    sed -i 's/^    gen &= 0xff;$/    \/\* CTRL: generation mask removed \*\//' \
        "$OUT"
fi

echo "✓ extracted ngx_http_cache_turbo_variant_hash → $(basename "$OUT")"
