#!/usr/bin/env bash
# Extract the production Cache-Control delta-seconds value parser verbatim.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_http_cache_turbo_module.c"
OUT="$DIR/generated_cc_delta.inc"

body="$(awk '
    capture { print; if ($0 == "}") { exit }; next }
    index($0, "ngx_http_cache_turbo_cc_parse_delta(") == 1 {
        capture = 1
        print "static time_t"
        print
        next
    }
' "$SRC")"

if [ -z "$body" ]; then
    echo "✗ failed to extract ngx_http_cache_turbo_cc_parse_delta from $SRC" >&2
    rm -f "$OUT"
    exit 1
fi

{
    echo "/* generated by ci/tests/unit/extract_cc_delta.sh — do not edit */"
    printf '%s\n' "$body"
} > "$OUT"

echo "✓ extracted Cache-Control delta parser → $(basename "$OUT")"
