#!/usr/bin/env bash
# Copyright (C) 2026 Thijs Eilander
# SPDX-License-Identifier: BSD-2-Clause
#
# Slice the verbatim bodies of the TWO stripe resolvers (P4-2-s3b) out of
# src/ngx_http_cache_turbo_module.h into generated_stripe_resolver.inc:
#
#   ngx_http_cache_turbo_stripe_of()     KEY-directed  -- key % nstripes
#   ngx_http_cache_turbo_zone_stripe()   ZONE-WIDE     -- hard &stripes[0]
#
# WHY A SLICE AND NOT A MIRROR. NGX_HTTP_CACHE_TURBO_STRIPES is pinned at 1 in
# production, so at the shipped N every input provably resolves to stripes[0]
# and NO runtime test can distinguish a correct resolver from a broken one.
# The only way to prove the key-directed resolver actually distributes is to
# compile it at a forced N > 1 -- which this slice does, against a
# locally-declared stripe/zone struct, with no nginx tree and no shm.
#
# The slice keeps the test honest in both directions: if someone changes the
# modulo, drops the nstripes<=1 fail-safe, or makes zone_stripe() key-directed,
# the PRODUCTION text is what gets recompiled here and the assertions move.
# A hand-mirror would have kept passing. (Same contract as
# extract_variant_hash.sh / extract_key_fold.sh -- the H-1/H-4 unpinned-mirror
# lesson.)
#
# Usage: ci/tests/unit/extract_stripe_resolver.sh   (no args; called from run.sh)
# Output: ci/tests/unit/generated_stripe_resolver.inc (overwritten; rm'd on fail)

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HDR="$DIR/../../../src/ngx_http_cache_turbo_module.h"
OUT="$DIR/generated_stripe_resolver.inc"

[ -f "$HDR" ] || { echo "extract_stripe_resolver: $HDR missing" >&2; exit 2; }

fail() { echo "extract_stripe_resolver: $*" >&2; rm -f "$OUT"; exit 1; }

# Slice one `static ngx_inline ngx_http_cache_turbo_stripe_t *\n<name>(...)`
# definition, from its return type through the closing brace in column 0.
slice() {
    awk -v fn="$1" '
        $0 == "static ngx_inline ngx_http_cache_turbo_stripe_t *" { pend = 1; buf = $0 "\n"; next }
        pend && index($0, fn "(") == 1 { on = 1; pend = 0; print buf $0; next }
        pend { pend = 0; next }
        on { print }
        on && /^}/ { on = 0; found = 1 }
        END { exit found ? 0 : 1 }
    ' "$HDR"
}

{
    echo "/* GENERATED by ci/tests/unit/extract_stripe_resolver.sh -- do not edit."
    echo " * Verbatim slice of the P4-2-s3b resolvers from"
    echo " * src/ngx_http_cache_turbo_module.h. */"
    echo
    slice ngx_http_cache_turbo_stripe_of   || fail "stripe_of() not found -- did the resolver move or change signature?"
    echo
    slice ngx_http_cache_turbo_zone_stripe || fail "zone_stripe() not found -- did the resolver move or change signature?"
} > "$OUT"

# Pin the two properties the test's whole argument rests on. Each is checked
# against the SLICE, so a header edit that keeps the name but guts the body is
# caught here rather than silently making the assertions vacuous.
grep -q 'key % (uint32_t) z->nstripes' "$OUT" \
    || fail "stripe_of() no longer distributes on 'key % nstripes' -- update the test's distribution argument, do not just repoint this grep"
grep -q 'z->nstripes <= 1' "$OUT" \
    || fail "stripe_of() lost its nstripes<=1 fail-safe -- an uninitialised zone would divide by zero"
grep -q 'return &z->stripes\[0\];' "$OUT" \
    || fail "zone_stripe() no longer hard-returns stripes[0]"

echo "extract_stripe_resolver: ok -> $(basename "$OUT")"
