#!/usr/bin/env bash
#
# Slice the verbatim body of the cache-turbo key-fold functions into
# generated_key_fold.inc:
#
#   ngx_http_cache_turbo_put_u32          little-endian u32 writer
#                                         (MAINT-SPLIT: now ../../../src/
#                                         ngx_http_cache_turbo_blob.c)
#   ngx_http_cache_turbo_key_fold_size    per-cookie size + oversize decision
#   ngx_http_cache_turbo_key_fold_append  per-cookie byte-framing (0x1f tag +
#                                         4B namelen + 4B vallen + name + value)
#   ngx_http_cache_turbo_key_fold_all     single-alloc fold over every queued
#                                         cookie (S231-PERF-KEYFOLD)
#                                         (the last three stay in
#                                         ../../../src/ngx_http_cache_turbo_module.c)
#
# S231-PERF-KEYFOLD replaced the old per-cookie realloc-and-copy-the-whole-key
# with a two-pass size-then-append over a single allocation. The digest that
# lands in ctx->key_hash must be BYTE-IDENTICAL to what the old code produced
# for the same inputs -- this is a cache key, so any value change silently
# invalidates every stored entry. test_key_fold.c pins the digest of known
# multi-part keys (including an empty-value part) against expected values
# computed from the byte-framing contract directly, using the REAL EVP/SHA-256
# digest via ngx_shim_digest -- so this test exercises PRODUCTION's own
# fold_size/fold_append/fold_all, not a mirror of them.
#
# If the functions can no longer be found we fail loudly rather than silently
# test nothing. Same contract as extract_variant_hash.sh / ci/fuzz/extract_blob.sh.
#
# Usage: ci/tests/unit/extract_key_fold.sh   (no args; called from run.sh)
# Output: ci/tests/unit/generated_key_fold.inc  (overwritten; removed on failure)

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/../../../src/ngx_http_cache_turbo_module.c"
SRC_BLOB="$DIR/../../../src/ngx_http_cache_turbo_blob.c"
OUT="$DIR/generated_key_fold.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

if [ ! -f "$SRC_BLOB" ]; then
    echo "✗ cannot find $SRC_BLOB" >&2
    exit 1
fi

{
    echo "/* generated by ci/tests/unit/extract_key_fold.sh — do not edit */"
    echo ""
} > "$OUT"

extract_fn() {
    local name="$1" src="$2"
    awk -v name="$name" '
        capture { print; if ($0 == "}") { capture = 0; print ""; exit }; next }
        index($0, name "(") == 1 { capture = 1; printf "%s", buf; print; buf = ""; next }
        { buf = $0 ORS }
    ' "$src"
}

# ngx_http_cache_turbo_put_u32 is non-static in blob.c (module.c calls it
# directly too); the other three stay static in module.c.
for spec in \
    "ngx_http_cache_turbo_put_u32:$SRC_BLOB" \
    "ngx_http_cache_turbo_key_fold_size:$SRC" \
    "ngx_http_cache_turbo_key_fold_append:$SRC" \
    "ngx_http_cache_turbo_key_cookie_queue:$SRC" \
    "ngx_http_cache_turbo_key_fold_all:$SRC"
do
    fn="${spec%%:*}"
    src="${spec#*:}"
    body="$(extract_fn "$fn" "$src")"
    if [ -z "$body" ]; then
        echo "✗ failed to extract $fn from $src" >&2
        echo "  (source layout changed? update extract_key_fold.sh)" >&2
        rm -f "$OUT"
        exit 1
    fi
    printf '%s\n' "$body" >> "$OUT"
done

# --- guard: fold_all must allocate the key buffer ONCE, not per queued
# cookie. S231-PERF-KEYFOLD's whole point was collapsing the old per-cookie
# ngx_pnalloc into a single sized allocation; a regression back to a
# realloc-per-entry loop would still pass a byte-identity test (same bytes,
# quadratic cost), so guard the shape here too.
if [ "$(grep -c 'ngx_pnalloc' "$OUT")" -ne 1 ]; then
    echo "✗ generated_key_fold.inc does not call ngx_pnalloc exactly once" >&2
    echo "  (S231-PERF-KEYFOLD requires ONE sized allocation, not one per cookie)" >&2
    rm -f "$OUT"
    exit 1
fi

echo "✓ extracted key-fold functions → $(basename "$OUT")"
