#!/usr/bin/env bash
#
# Slice the verbatim bodies of the cache-turbo L2 BLOB deserializer out of the
# shipped ../../src/ngx_http_cache_turbo_module.c into generated_blob.inc:
#
#   ngx_http_cache_turbo_get_u16/_u32/_u64   fixed-endian wire accessors
#   ngx_http_cache_turbo_blob_validate()     framing + range validation
#   ngx_http_cache_turbo_blob_next_header()  the TLV header-walk iterator that
#                                            restore_response() itself drives
#   ngx_http_cache_turbo_header_skip()       the store/restore drop list
#   ngx_http_cache_turbo_header_admissible() the single admissibility gate both
#                                            directions call
#
# Captured in source order so the .inc compiles standalone (each callee is
# defined before its caller: the get_u* accessors precede blob_validate, and
# header_skip precedes header_admissible).
#
# This keeps the fuzz target locked to production code — there is no hand-copied
# deserializer. If a body changes upstream the next fuzz build picks it up; if a
# function can no longer be found we fail loudly rather than silently fuzz
# nothing. Same contract as extract_parser.sh / extract_mc_parser.sh.
#
# Usage: ci/fuzz/extract_blob.sh   (no args; called from ci/fuzz/build.sh)
# Output: ci/fuzz/generated_blob.inc  (overwritten; removed on any failure)

set -euo pipefail

FUZZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$FUZZ_DIR/../../src/ngx_http_cache_turbo_module.c"
HDR="$FUZZ_DIR/../../src/ngx_http_cache_turbo_module.h"
OUT="$FUZZ_DIR/generated_blob.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

# --- guard: the wire constants the harness hard-codes must still match the
# header. The harness builds its own seed blobs against these offsets; a drift
# would make it fuzz a layout production no longer writes. Fail the build.
emit_defines() {
    for name in NGX_HTTP_CACHE_TURBO_BLOB_MAGIC \
                NGX_HTTP_CACHE_TURBO_BLOB_VERSION \
                NGX_HTTP_CACHE_TURBO_BLOB_HDR_WIRE \
                NGX_HTTP_CACHE_TURBO_TTL_MAX \
                NGX_HTTP_CACHE_TURBO_FOREVER_TTL \
                NGX_HTTP_CACHE_TURBO_BLOB_CREATED_MIN
    do
        line=$(grep -E "^#define[[:space:]]+${name}[[:space:]]" "$HDR" | head -n1)
        if [ -z "$line" ]; then
            echo "✗ $name not found in $HDR (renamed? update extract_blob.sh)" >&2
            exit 1
        fi
        echo "$line"
    done
}

{
    echo "/* generated by ci/fuzz/extract_blob.sh — do not edit */"
    emit_defines
    echo ""
    # The PARSED header struct, sliced (not mirrored) so a field rename upstream
    # is a compile error in the harness rather than a silent type mismatch.
    awk '/^typedef struct \{/ { buf = $0 ORS; cap = 1; next }
         cap { buf = buf $0 ORS
               if ($0 ~ /^\} ngx_http_cache_turbo_blob_hdr_t;/) { printf "%s", buf; exit }
               if ($0 ~ /^\} /) { cap = 0; buf = "" } }' "$HDR"
} > "$OUT"

if ! grep -qF '} ngx_http_cache_turbo_blob_hdr_t;' "$OUT"; then
    echo "✗ could not slice ngx_http_cache_turbo_blob_hdr_t from $HDR" >&2
    rm -f "$OUT"
    exit 1
fi

# --- slice the function bodies, in source order.
# nginx style: the return type sits alone on one line, the name+params line
# follows, and the body closes on a bare `}` in column 0.
awk '
    /^static / { pending = 1; buf = $0 ORS; next }
    pending && /^ngx_http_cache_turbo_(get_u(16|32|64)|blob_validate|blob_next_header|header_skip|header_admissible)\(/ {
        capture = 1; pending = 0; printf "%s", buf; print; next
    }
    pending { pending = 0; buf = "" }
    capture {
        print
        if ($0 == "}") { capture = 0; print "" }
    }
' "$SRC" >> "$OUT"

# --- sanity: every function must be present and the file must end on a brace.
for fn in \
    'ngx_http_cache_turbo_get_u16(' \
    'ngx_http_cache_turbo_get_u32(' \
    'ngx_http_cache_turbo_get_u64(' \
    'ngx_http_cache_turbo_blob_validate(' \
    'ngx_http_cache_turbo_blob_next_header(' \
    'ngx_http_cache_turbo_header_skip('
do
    if ! grep -qF "$fn" "$OUT"; then
        echo "✗ failed to extract $fn from $SRC" >&2
        echo "  (source layout changed? update extract_blob.sh)" >&2
        rm -f "$OUT"
        exit 1
    fi
done
# --- the admissibility gate is detected, NOT required.
# When it is absent the harness must model production faithfully: restore emits
# every header blob_validate accepted, unfiltered. That is what makes this
# target go RED on today's-code-without-the-fix (and RED again if someone later
# deletes the helper) instead of silently asserting nothing. Do not turn this
# into a hard requirement — the knob IS the regression guard.
if grep -qF 'ngx_http_cache_turbo_header_admissible(' "$OUT"; then
    echo "#define CT_HAVE_HEADER_ADMISSIBLE 1" >> "$OUT"
    echo "  · header_admissible() present — restore-side filter is under test"
else
    echo "#define CT_HAVE_HEADER_ADMISSIBLE 0" >> "$OUT"
    echo "  ⚠ header_admissible() ABSENT — modelling an unfiltered restore" >&2
fi

if [ "$(grep -c . "$OUT")" -lt 60 ]; then
    echo "✗ generated_blob.inc is implausibly short (bad slice)" >&2
    rm -f "$OUT"
    exit 1
fi

LINES=$(wc -l < "$OUT")
echo "✓ extracted blob_validate() + blob_next_header() + header_admissible()" \
     "— $LINES lines -> $OUT"
