#!/usr/bin/env bash
#
# Slice the verbatim bodies of the cache-turbo L2 BLOB deserializer into
# generated_blob.inc:
#
#   ngx_http_cache_turbo_get_u16/_u32/_u64   fixed-endian wire accessors
#   ngx_http_cache_turbo_blob_validate()     framing + range validation
#   ngx_http_cache_turbo_blob_next_header()  the TLV header-walk iterator that
#                                            restore_response() itself drives
#   ngx_http_cache_turbo_header_skip()       the store/restore drop list
#   ngx_http_cache_turbo_header_admissible() the single admissibility gate both
#                                            directions call
#
# Captured in source order so the .inc compiles standalone (each callee is
# defined before its caller: the get_u* accessors precede blob_validate, and
# header_skip precedes header_admissible).
#
# MAINT-SPLIT: get_u16/_u32/_u64, blob_validate and blob_next_header now live
# in ../../src/ngx_http_cache_turbo_blob.c; header_skip/header_admissible*
# stay in ../../src/ngx_http_cache_turbo_module.c (they are called from many
# more module.c sites and were not part of this move). Slice both files in
# the SAME order the .inc has always needed and concatenate.
#
# This keeps the fuzz target locked to production code — there is no hand-copied
# deserializer. If a body changes upstream the next fuzz build picks it up; if a
# function can no longer be found we fail loudly rather than silently fuzz
# nothing. Same contract as extract_parser.sh / extract_mc_parser.sh.
#
# Usage: ci/fuzz/extract_blob.sh   (no args; called from ci/fuzz/build.sh)
# Output: ci/fuzz/generated_blob.inc  (overwritten; removed on any failure)

set -euo pipefail

FUZZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$FUZZ_DIR/../../src/ngx_http_cache_turbo_module.c"
SRC_BLOB="$FUZZ_DIR/../../src/ngx_http_cache_turbo_blob.c"
# ⚠ The wire constants below span TWO headers as of MAINT-C3b: the BLOB_* ones
# are module.c-private and live in _internal.h, while TTL_MAX and FOREVER_TTL
# stay public in module.h. This extractor is a NON-COMPILER consumer of those
# declarations, so a move between headers breaks THIS grep rather than any
# build. Search both; the names are unique across them.
HDR_PUB="$FUZZ_DIR/../../src/ngx_http_cache_turbo_module.h"
HDR_INT="$FUZZ_DIR/../../src/ngx_http_cache_turbo_internal.h"
HDRS=("$HDR_PUB" "$HDR_INT")
# blob_hdr_t and blob_href_t are module.c-private and sliced from _internal.h.
HDR_STRUCTS="$HDR_INT"
OUT="$FUZZ_DIR/generated_blob.inc"

if [ ! -f "$SRC" ]; then
    echo "✗ cannot find $SRC" >&2
    exit 1
fi

if [ ! -f "$SRC_BLOB" ]; then
    echo "✗ cannot find $SRC_BLOB" >&2
    exit 1
fi

# --- guard: the wire constants the harness hard-codes must still match the
# header. The harness builds its own seed blobs against these offsets; a drift
# would make it fuzz a layout production no longer writes. Fail the build.
emit_defines() {
    for name in NGX_HTTP_CACHE_TURBO_BLOB_MAGIC \
                NGX_HTTP_CACHE_TURBO_BLOB_VERSION \
                NGX_HTTP_CACHE_TURBO_BLOB_HDR_WIRE \
                NGX_HTTP_CACHE_TURBO_TTL_MAX \
                NGX_HTTP_CACHE_TURBO_FOREVER_TTL \
                NGX_HTTP_CACHE_TURBO_BLOB_CREATED_MIN \
                NGX_HTTP_CACHE_TURBO_BLOBF_HDRS_VETTED \
                NGX_HTTP_CACHE_TURBO_BLOB_DATE_LEN \
                NGX_HTTP_CACHE_TURBO_BLOB_DATE_OFF \
                NGX_HTTP_CACHE_TURBO_HROLE_OTHER \
                NGX_HTTP_CACHE_TURBO_HROLE_CONTENT_TYPE \
                NGX_HTTP_CACHE_TURBO_HROLE_ETAG \
                NGX_HTTP_CACHE_TURBO_HROLE_LAST_MODIFIED \
                NGX_HTTP_CACHE_TURBO_HROLE_MAX
    do
        # A name defined in more than one header is itself drift: the harness
        # would silently take whichever came first. Collect every hit.
        # `|| true`: grep exits 1 when the constant is absent, and under
        # `set -e` that kills the function BEFORE the diagnostic below runs --
        # the build then fails with no message at all. Keep the guard's own
        # error reachable.
        hits=$(grep -hE "^#define[[:space:]]+${name}[[:space:]]" "${HDRS[@]}" || true)
        n=$(printf '%s\n' "$hits" | grep -c . || true)
        if [ "$n" -eq 0 ]; then
            echo "✗ $name not found in ${HDRS[*]} (renamed or moved?" \
                 "update extract_blob.sh)" >&2
            exit 1
        fi
        if [ "$n" -gt 1 ]; then
            echo "✗ $name defined $n times across the module headers —" \
                 "the harness cannot tell which layout production writes" >&2
            exit 1
        fi
        printf '%s\n' "$hits"
    done
}

{
    echo "/* generated by ci/fuzz/extract_blob.sh — do not edit */"
    emit_defines
    echo ""
    # The PARSED header struct, sliced (not mirrored) so a field rename upstream
    # is a compile error in the harness rather than a silent type mismatch.
    awk '/^typedef struct \{/ { buf = $0 ORS; cap = 1; next }
         cap { buf = buf $0 ORS
               if ($0 ~ /^\} ngx_http_cache_turbo_blob_hdr_t;/) { printf "%s", buf; exit }
               if ($0 ~ /^\} /) { cap = 0; buf = "" } }' "$HDR_STRUCTS"
    echo ""
    # S231-PERF-HDRWALK: the parsed-header-ref struct blob_validate() now fills
    # in the same walk blob_next_header() drives. Same slice-not-mirror
    # reasoning as the struct above.
    awk '/^typedef struct \{/ { buf = $0 ORS; cap = 1; next }
         cap { buf = buf $0 ORS
               if ($0 ~ /^\} ngx_http_cache_turbo_blob_href_t;/) { printf "%s", buf; exit }
               if ($0 ~ /^\} /) { cap = 0; buf = "" } }' "$HDR_STRUCTS"
    echo ""
    # S231-PERF-HDRWALK: blob_validate() now calls blob_next_header() (defined
    # further down in module.c, same as production), so the harness needs the
    # same forward declaration module.c carries.
    echo "static ngx_int_t ngx_http_cache_turbo_blob_next_header(const u_char **pp,"
    echo "    const u_char *end, const u_char **name, uint32_t *nlen,"
    echo "    const u_char **val, uint32_t *vlen, uint32_t *role);"
    echo ""
} > "$OUT"

if ! grep -qF '} ngx_http_cache_turbo_blob_hdr_t;' "$OUT"; then
    echo "✗ could not slice ngx_http_cache_turbo_blob_hdr_t from $HDR_STRUCTS" >&2
    rm -f "$OUT"
    exit 1
fi

if ! grep -qF '} ngx_http_cache_turbo_blob_href_t;' "$OUT"; then
    echo "✗ could not slice ngx_http_cache_turbo_blob_href_t from $HDR_STRUCTS" >&2
    rm -f "$OUT"
    exit 1
fi

# --- slice the function bodies, in source order.
# nginx style: the return type sits alone on one line, the name+params line
# follows, and the body closes on a bare `}` in column 0.
# get_u16/_u32/_u64, blob_validate, blob_next_header: ngx_http_cache_turbo_blob.c
# (MAINT-SPLIT made get_u16/_u32/_u64 and blob_validate non-static, since
# module.c calls them directly, so the return-type line no longer starts with
# `static` for those two -- match ANY line that is not itself the function's
# own name+params line as the "pending" return-type line, not just a
# static-prefixed one).
# header_skip, header_admissible*: still ngx_http_cache_turbo_module.c, still static.
slice_fns() {
    local pattern="$1" src="$2"
    awk -v pattern="$pattern" '
        capture { print; if ($0 == "}") { capture = 0; print "" }; next }
        $0 ~ pattern { capture = 1; printf "%s", buf; print; buf = ""; next }
        { buf = $0 ORS }
    ' "$src"
}

# P4-3: put_u16 and blob_clear_vetted are sliced too. The harness's input
# stands in for bytes read out of L2, so it MUST run the same ingress
# demotion redis.c/memcached.c apply before anything downstream reads the
# blob -- otherwise the harness would be fuzzing a trust level production
# never grants to L2 bytes. Sliced, not mirrored, for the same reason as
# every other function here: a change to the real clearing is a change to
# the harness.
slice_fns '^ngx_http_cache_turbo_(get_u(16|32|64)|put_u16|blob_validate|blob_next_header|blob_clear_vetted)[(]' \
    "$SRC_BLOB" >> "$OUT"
slice_fns '^ngx_http_cache_turbo_(header_skip|header_admissible|header_admissible_name|header_admissible_value)[(]' \
    "$SRC" >> "$OUT"

# --- sanity: every function must be present and the file must end on a brace.
for fn in \
    'ngx_http_cache_turbo_get_u16(' \
    'ngx_http_cache_turbo_get_u32(' \
    'ngx_http_cache_turbo_get_u64(' \
    'ngx_http_cache_turbo_blob_validate(' \
    'ngx_http_cache_turbo_blob_next_header(' \
    'ngx_http_cache_turbo_header_skip(' \
    'ngx_http_cache_turbo_put_u16(' \
    'ngx_http_cache_turbo_blob_clear_vetted('
do
    if ! grep -qF "$fn" "$OUT"; then
        echo "✗ failed to extract $fn from $SRC / $SRC_BLOB" >&2
        echo "  (source layout changed? update extract_blob.sh)" >&2
        rm -f "$OUT"
        exit 1
    fi
done
# --- the admissibility gate is detected, NOT required.
# When it is absent the harness must model production faithfully: restore emits
# every header blob_validate accepted, unfiltered. That is what makes this
# target go RED on today's-code-without-the-fix (and RED again if someone later
# deletes the helper) instead of silently asserting nothing. Do not turn this
# into a hard requirement — the knob IS the regression guard.
if grep -qF 'ngx_http_cache_turbo_header_admissible(' "$OUT"; then
    echo "#define CT_HAVE_HEADER_ADMISSIBLE 1" >> "$OUT"
    echo "  · header_admissible() present — restore-side filter is under test"
else
    echo "#define CT_HAVE_HEADER_ADMISSIBLE 0" >> "$OUT"
    echo "  ⚠ header_admissible() ABSENT — modelling an unfiltered restore" >&2
fi

if [ "$(grep -c . "$OUT")" -lt 60 ]; then
    echo "✗ generated_blob.inc is implausibly short (bad slice)" >&2
    rm -f "$OUT"
    exit 1
fi

LINES=$(wc -l < "$OUT")
echo "✓ extracted blob_validate() + blob_next_header() + header_admissible()" \
     "— $LINES lines -> $OUT"
