/*
 * libFuzzer harness for the cache-turbo RESP reply parsers:
 *   ngx_http_cache_turbo_redis_parse()        - bulk-string GET reply
 *   ngx_http_cache_turbo_redis_parse_array()  - SMEMBERS array reply
 *   ngx_http_cache_turbo_redis_parse_scan()   - SCAN [cursor, keys] 2-tuple
 *   ngx_http_cache_turbo_redis_frame()        - STAB-3 pre-framer (recursive)
 *
 * Why this target: these functions parse a Redis reply — attacker-influenceable
 * bytes from a shared, possibly buggy or compromised L2 — doing length-line and
 * bulk-string pointer arithmetic against op->rbuf .. op->rbuf + op->rlen. A
 * single off-by-one in a CRLF scan or a length check is a worker-crashing OOB
 * read. The parsers are fully length-bounded (no NUL reliance), so this harness
 * feeds a buffer sized EXACTLY to op->rlen with NO trailing NUL: ASAN then turns
 * any read at or past the end — i.e. any reintroduced NUL-bounded scan or
 * off-by-one — into an immediate, reproducible heap-buffer-overflow.
 *
 * The real parser bodies live in ../../src/ngx_http_cache_turbo_redis.c and depend
 * on the nginx tree; ci/fuzz/extract_parser.sh slices just those four functions
 * into generated_parser.inc at build time, so we always fuzz the SHIPPED code
 * with no copy drift. ngx_shim.h supplies the tiny nginx surface they need
 * (op struct, pool, ngx_atoi/ngx_strlchr) with faithful upstream semantics.
 *
 * Build (see ci/fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_resp_parser.c -o fuzz_resp_parser
 */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by ci/fuzz/extract_parser.sh from
 * ../../src/ngx_http_cache_turbo_redis.c. Contains the verbatim bodies of the
 * three RESP parsers in source order. */
#include "generated_parser.inc"

static void check_split_delivery(u_char *buf, size_t size, ngx_pool_t *pool);

/* Validate that an ngx_str_t the parser handed back references INTO the input
 * buffer (or is the empty/NULL nil sentinel), never outside it. A parser that
 * returns NGX_OK with a member pointing past the buffer is a bug ASAN would not
 * otherwise see (the read happens later, in the caller). */
static void
check_in_bounds(const u_char *blob, size_t blob_len,
    const u_char *buf, size_t size)
{
    uintptr_t  blob_addr, buf_addr, offset;

    if (blob == NULL) {
        if (blob_len != 0) {
            __builtin_trap();              /* NULL data with nonzero len */
        }
        return;
    }
    blob_addr = (uintptr_t) blob;
    buf_addr = (uintptr_t) buf;
    if (blob_addr < buf_addr) {
        __builtin_trap();
    }
    offset = blob_addr - buf_addr;
    if (offset > (uintptr_t) size
        || blob_len > size - (size_t) offset)
    {
        __builtin_trap();                  /* points outside the input buffer */
    }
}

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    ngx_pool_t  pool;
    u_char     *buf;
    size_t      alloc;

    pool.nallocs = 0;

    /*
     * Allocate EXACTLY `size` bytes (one byte when size == 0, since malloc(0)
     * is implementation-defined) and do NOT NUL-terminate: any read at or past
     * ae->len / op->rlen becomes an ASAN heap-buffer-overflow.
     */
    alloc = size ? size : 1;
    buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (size) {
        memcpy(buf, data, size);
    }

    /* 1) GET bulk-string parser. */
    {
        ngx_http_cache_turbo_redis_op_t  op;
        u_char    *blob = NULL;
        size_t     blob_len = 0;
        ngx_int_t  rc;

        op.rbuf = buf;
        op.rlen = size;
        op.pool = &pool;
        op.rpool = &pool;

        rc = ngx_http_cache_turbo_redis_parse(&op, &blob, &blob_len);
        /* L13-fix: this parser is TRI-state on failure. NGX_DECLINED is now
         * reserved for a well-formed `$-1` nil (a DEFINITIVE miss, the only
         * outcome allowed to arm the L13 negative memo) and NGX_ERROR covers
         * every not-an-answer reply: a Redis error reply, an unexpected type
         * byte, an unparsable length, an oversized payload. Both are legal
         * returns; conflating them is the bug the split exists to prevent. */
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED
            && rc != NGX_ERROR)
        {
            __builtin_trap();              /* undocumented return */
        }
        if (rc == NGX_OK) {
            check_in_bounds(blob, blob_len, buf, size);
        }
        /* A failure return must never hand back a blob. */
        if (rc != NGX_OK && (blob != NULL || blob_len != 0)) {
            __builtin_trap();
        }
        ngx_fuzz_pool_reset(&pool);
    }

    /* 2) SMEMBERS array parser. */
    {
        ngx_http_cache_turbo_redis_op_t  op;
        ngx_str_t  *members = NULL;
        ngx_uint_t  nmembers = 0;
        ngx_int_t   rc;

        op.rbuf = buf;
        op.rlen = size;
        op.pool = &pool;
        op.rpool = &pool;

        rc = ngx_http_cache_turbo_redis_parse_array(&op, &members, &nmembers);
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED) {
            __builtin_trap();
        }
        if (rc == NGX_OK) {
            for (ngx_uint_t i = 0; i < nmembers; i++) {
                check_in_bounds(members[i].data, members[i].len, buf, size);
            }
        }
        ngx_fuzz_pool_reset(&pool);
    }

    /* 3) SCAN 2-tuple parser. */
    {
        ngx_http_cache_turbo_redis_op_t  op;
        ngx_str_t   cursor = { 0, NULL };
        ngx_str_t  *keys = NULL;
        ngx_uint_t  nkeys = 0;
        ngx_int_t   rc;

        op.rbuf = buf;
        op.rlen = size;
        op.pool = &pool;
        op.rpool = &pool;

        rc = ngx_http_cache_turbo_redis_parse_scan(&op, &cursor, &keys, &nkeys);
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED) {
            __builtin_trap();
        }
        if (rc == NGX_OK) {
            check_in_bounds(cursor.data, cursor.len, buf, size);
            for (ngx_uint_t i = 0; i < nkeys; i++) {
                check_in_bounds(keys[i].data, keys[i].len, buf, size);
            }
        }
        ngx_fuzz_pool_reset(&pool);
    }

    /* 4) STAB-3 pre-framer. Unlike the three above it takes raw pointers rather
     * than an op, reports progress through *next, and is the module's ONLY
     * recursive parser: a `*<count>` array recurses per element, bounded by
     * FRAME_MAX_DEPTH. It is the pre-framer for read_smembers/read_scan and,
     * since PR #233, the keepalive clean gate in read_lock depends on it too —
     * so a frame that reports the wrong end advances the read cursor onto
     * attacker-chosen bytes.
     *
     * Oracle: on NGX_OK, *next must land within [buf, buf + size]. Landing past
     * the end means the caller's next frame() starts out of bounds; landing
     * before the start means pointer arithmetic underflowed. Neither is
     * something ASAN catches here — the bad read happens later, in the caller —
     * so it is asserted explicitly. next == buf + size is legal: the frame
     * consumed the buffer exactly.
     *
     * A non-OK return must not be trusted to have set *next at all, so it is
     * only checked on NGX_OK. The sentinel below would be outside the buffer,
     * which is precisely what makes it a usable "was it written" marker. */
    {
        u_char    *next = NULL;
        ngx_int_t  rc;

        rc = ngx_http_cache_turbo_redis_frame(buf, buf + size, 0, &next);
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED) {
            __builtin_trap();              /* undocumented return */
        }
        if (rc == NGX_OK) {
            if (next == NULL) {
                __builtin_trap();          /* OK but never reported an end */
            }
            if ((uintptr_t) next < (uintptr_t) buf
                || (uintptr_t) next > (uintptr_t) buf + size)
            {
                __builtin_trap();          /* cursor outside the input buffer */
            }
        }
        ngx_fuzz_pool_reset(&pool);
    }

    /* 5) SPLIT DELIVERY. Everything above hands the parser one buffer holding
     * the whole reply, which is the single case a real socket does NOT
     * guarantee: a Redis reply arrives in as many recv()s as the network feels
     * like, and read_get()/read_smembers()/read_scan() drive their parser in a
     * loop — parse, get NGX_AGAIN, fill() more bytes into the SAME growing
     * buffer, parse the whole thing again from the start.
     *
     * That resume path is what is untested. A parser that is correct on a
     * complete buffer can still be wrong across a split: caching a CRLF offset
     * that moves when the buffer is reallocated, treating a truncated length
     * line as final rather than incomplete, or returning a blob that points
     * into the PREVIOUS allocation. None of those are reachable from a
     * single-shot target, and none are what the corpus above explores.
     *
     * Modelled faithfully rather than approximately: op->rbuf is REALLOCATED at
     * each step (fill() grows by doubling, so the parser must never hold a
     * pointer across calls) and op->rlen grows by the prefix length.
     *
     * ⚠ The whole input IS the reply — no byte is stolen from it to choose the
     * split point. An earlier revision took the split from data[0] and parsed
     * data+1, which corrupted every corpus entry (they are complete replies
     * starting at byte 0): all 362 inputs returned NGX_ERROR at the resume step
     * and the byte-comparison oracle below was dead code. Verified by probe,
     * not assumed. The split is derived from the LENGTH instead, and every
     * boundary is swept, so a corpus entry that parses in one piece is
     * guaranteed to reach the comparison — for each of its split points.
     *
     * ⚠ Oracle, and the reason this is not just "run the parser twice": feeding
     * a prefix must yield NGX_AGAIN, and feeding the complete reply must yield
     * the SAME verdict the single-shot parse of those bytes gave, with a blob
     * that compares byte-for-byte. A parser that resumes wrongly typically
     * still returns NGX_OK — with a short, shifted or stale blob — so a return
     * code alone would certify the bug. The bytes are the oracle. */
    check_split_delivery(buf, size, &pool);

    free(buf);
    return 0;
}


/* Body of block 5, split out of LLVMFuzzerTestOneInput: it is the only block
 * with real control flow of its own (a sweep over split points, each running a
 * two-step feed), and inlining it pushed the driver's cyclomatic complexity to
 * 56 -- past the point where the harness reads as a list of independent
 * parser checks, which is the property that makes it reviewable. */
static void
check_split_delivery(u_char *buf, size_t size, ngx_pool_t *pool)
{
    if (size >= 2) {
        u_char    *whole = NULL;
        size_t     whole_len = 0, split;
        ngx_int_t  rc_whole;

        /* Reference verdict: the identical bytes parsed in one piece. */
        {
            ngx_http_cache_turbo_redis_op_t  ref;
            u_char  *blob = NULL;
            size_t   blob_len = 0;

            ref.rbuf = buf;
            ref.rlen = size;
            ref.pool = pool;
            ref.rpool = pool;

            rc_whole = ngx_http_cache_turbo_redis_parse(&ref, &blob, &blob_len);

            /* Copy the reference blob out: it points into `buf`, and the split
             * feed below parses out of its own reallocated buffers. */
            if (rc_whole == NGX_OK && blob != NULL && blob_len != 0) {
                whole = (u_char *) malloc(blob_len);
                if (whole == NULL) {
                    /* buf belongs to the caller — it frees it. */
                    ngx_fuzz_pool_reset(pool);
                    return;
                }
                memcpy(whole, blob, blob_len);
                whole_len = blob_len;
            }
            ngx_fuzz_pool_reset(pool);
        }

        /* Sweep EVERY boundary rather than sampling one. The reply is short
         * (libFuzzer caps these inputs at a few hundred bytes) and the split
         * point is exactly the variable that decides whether a resume is
         * correct — a length line cut mid-digit, a CRLF cut between its two
         * bytes, a bulk body cut one short. Sampling would leave the
         * interesting boundaries to chance. */
        for (split = 1; split < size; split++) {
            ngx_http_cache_turbo_redis_op_t  op;
            u_char    *grow;
            size_t     step;
            ngx_int_t  rc = NGX_AGAIN;

            op.rbuf = NULL;
            op.rlen = 0;
            op.pool = pool;
            op.rpool = pool;

            for (step = 0; step < 2; step++) {
                size_t  have = step == 0 ? split : size;
                u_char *blob = NULL;
                size_t  blob_len = 0;

                /* fill() grows by doubling into a FRESH allocation and copies
                 * the bytes over, so the parser must never retain a pointer
                 * across calls. Reallocating here is what turns a retained
                 * pointer into an ASAN use-after-free instead of a silently
                 * stale read that still happens to hold the right bytes. */
                grow = (u_char *) malloc(have);
                if (grow == NULL) {
                    break;
                }
                memcpy(grow, buf, have);
                if (op.rbuf != NULL) {
                    free(op.rbuf);
                }
                op.rbuf = grow;
                op.rlen = have;

                rc = ngx_http_cache_turbo_redis_parse(&op, &blob, &blob_len);

                if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED
                    && rc != NGX_ERROR)
                {
                    __builtin_trap();      /* undocumented return */
                }
                if (rc != NGX_OK && (blob != NULL || blob_len != 0)) {
                    __builtin_trap();      /* failure handed back a blob */
                }
                if (rc == NGX_OK) {
                    check_in_bounds(blob, blob_len, op.rbuf, op.rlen);
                }

                if (step == 0) {
                    /* A strict prefix of a reply that parses whole cannot be a
                     * complete answer: the parser must ask for more, not invent
                     * a verdict from truncated bytes. (Only checked when the
                     * whole reply parses — for malformed input the parser is
                     * entitled to reject the prefix outright.)
                     * A successful whole parse now proves the reply consumes
                     * the entire input exactly, so every split below `size` is
                     * necessarily inside that reply. */
                    if (rc_whole == NGX_OK && rc == NGX_OK) {
                        __builtin_trap();  /* answered from a partial reply */
                    }
                    continue;
                }

                /* step 1: the full reply is present. The verdict must match the
                 * single-shot parse of the identical bytes, and so must the
                 * payload. A resume that goes wrong typically still returns
                 * NGX_OK with a short, shifted or stale blob, so the BYTES are
                 * the oracle — a return-code check alone would certify it. */
                if (rc != rc_whole) {
                    __builtin_trap();      /* split changed the verdict */
                }
                if (rc == NGX_OK) {
                    if (blob_len != whole_len) {
                        __builtin_trap();  /* resumed parse changed the length */
                    }
                    if (whole_len != 0
                        && memcmp(blob, whole, whole_len) != 0)
                    {
                        __builtin_trap();  /* resumed parse changed the bytes */
                    }
                }
            }

            if (op.rbuf != NULL) {
                free(op.rbuf);
            }
            ngx_fuzz_pool_reset(pool);
        }

        free(whole);
    }
}

#if defined(NGX_HTTP_CACHE_TURBO_RESP_FIXTURES)
static int
check_get_fixture(const char *name, const u_char *wire, size_t wire_len,
    ngx_int_t want, const u_char *want_blob, size_t want_blob_len)
{
    ngx_pool_t                       pool = { 0 };
    ngx_http_cache_turbo_redis_op_t  op = { 0 };
    u_char                          *blob = NULL;
    size_t                           blob_len = 0;
    ngx_int_t                        got;

    op.rbuf = (u_char *) wire;
    op.rlen = wire_len;
    op.pool = &pool;
    op.rpool = &pool;

    got = ngx_http_cache_turbo_redis_parse(&op, &blob, &blob_len);
    if (got != want) {
        fprintf(stderr, "%s: got rc=%ld, want rc=%ld\n",
                name, (long) got, (long) want);
        return 1;
    }
    if (got == NGX_OK
        && (blob_len != want_blob_len
            || memcmp(blob, want_blob, want_blob_len) != 0))
    {
        fprintf(stderr, "%s: payload mismatch\n", name);
        return 1;
    }
    if (got != NGX_OK && (blob != NULL || blob_len != 0)) {
        fprintf(stderr, "%s: failure returned a payload\n", name);
        return 1;
    }
    return 0;
}


int
main(void)
{
    int  failures = 0;

    failures += check_get_fixture("exact hit",
        (const u_char *) "$3\r\nfoo\r\n", sizeof("$3\r\nfoo\r\n") - 1,
        NGX_OK, (const u_char *) "foo", 3);
    failures += check_get_fixture("exact nil",
        (const u_char *) "$-1\r\n", sizeof("$-1\r\n") - 1,
        NGX_DECLINED, NULL, 0);
    failures += check_get_fixture("partial payload",
        (const u_char *) "$3\r\nfo", sizeof("$3\r\nfo") - 1,
        NGX_AGAIN, NULL, 0);
    failures += check_get_fixture("wrong payload delimiter",
        (const u_char *) "$3\r\nfooXX", sizeof("$3\r\nfooXX") - 1,
        NGX_ERROR, NULL, 0);
    failures += check_get_fixture("trailing partial reply after hit",
        (const u_char *) "$3\r\nfoo\r\n+", sizeof("$3\r\nfoo\r\n+") - 1,
        NGX_ERROR, NULL, 0);
    failures += check_get_fixture("trailing partial reply after nil",
        (const u_char *) "$-1\r\n+", sizeof("$-1\r\n+") - 1,
        NGX_ERROR, NULL, 0);

    if (failures == 0) {
        fprintf(stderr, "RESP GET fixtures: 6 checks, 0 failures\n");
    }
    return failures != 0;
}
#endif
