/*
 * libFuzzer harness for the cache-turbo L2 BLOB deserializer:
 *   ngx_http_cache_turbo_blob_validate()      framing + range validation
 *   ngx_http_cache_turbo_blob_next_header()   the TLV header-walk iterator
 *   ngx_http_cache_turbo_header_admissible()  the restore-side admissibility gate
 *
 * Why this target (AUD-FUZZ1): the other four harnesses stop at the RESP /
 * memcached wire boundary and hand off a blob that nothing then fuzzes. This is
 * the single stage that turns hostile L2 bytes into HTTP RESPONSE HEADERS — an
 * attacker with L2 write access (compromised Redis, or a MITM'd one, see
 * AUD-TLS1) picks the (name, value) pairs nginx then writes out verbatim as
 * `key: value\r\n`. A CR/LF in a value is response splitting; a smuggled
 * `Transfer-Encoding` or second `Content-Length` is request smuggling against a
 * downstream proxy or CDN; a `Set-Cookie` is session fixation.
 *
 * The oracle is therefore not just "don't crash". On every blob the validator
 * ACCEPTS, this harness asserts the contract every consumer of that blob
 * inherits:
 *
 *   1. status is a real HTTP status (100..599)
 *   2. stale_ttl >= fresh_ttl  — the store side's own documented invariant
 *      (stale_ttl is the TOTAL serveable window; see the blob_hdr layout
 *      comment in the module header)
 *   3. every TTL is <= NGX_HTTP_CACHE_TURBO_TTL_MAX
 *   4. the header block and body lie inside the input buffer
 *   5. every (name,len)/(value,len) the walk yields lies inside the buffer
 *   6. every header restore would EMIT has a valid HTTP token name (RFC 9110
 *      §5.6.2) and a value free of CR, LF and NUL
 *   7. (P4-3) the blob does NOT carry BLOBF_HDRS_VETTED once the L2 ingress
 *      demotion has run. That bit switches assertion (6)'s production gate
 *      OFF, so an L2 writer able to set it owns the response-splitting
 *      primitive outright; the harness runs the real
 *      ngx_http_cache_turbo_blob_clear_vetted() over the input first, exactly
 *      as redis.c/memcached.c do, then asserts the demotion held.
 *
 * (6) is the AUD-HDR1 assertion. What "would emit" means is read from the
 * SHIPPED code, not modelled here: when src/ngx_http_cache_turbo_module.c
 * defines ngx_http_cache_turbo_header_admissible(), extract_blob.sh sets
 * CT_HAVE_HEADER_ADMISSIBLE=1 and this harness routes every pair through the
 * production gate. When it does NOT — i.e. on the unfixed tree, or if someone
 * later deletes the helper — the knob is 0 and the harness models an unfiltered
 * restore, which is exactly what production does in that state. So this target
 * goes RED on the defect and stays RED if the fix is reverted; it can never
 * quietly assert nothing.
 *
 * As with the other targets the input buffer is allocated to EXACTLY `size`
 * with no trailing NUL, so any reintroduced NUL-bounded scan or off-by-one in
 * the walk is an immediate ASan heap-buffer-overflow.
 *
 * Build (see ci/fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined fuzz_blob.c -o fuzz_blob
 *   clang -g -O1 -fsanitize=address,undefined -DCT_BLOB_FIXTURES \
 *       fuzz_blob.c -o fuzz_blob_fixtures
 *
 * The fixture binary (-DCT_BLOB_FIXTURES) is the deterministic per-primitive
 * suite the unit gate runs: one named fixture per AUD-HDR1 primitive, each with
 * its own failure message so a mutation red names the guard it disarmed. It
 * also doubles as the seed-corpus writer (--write-corpus DIR), so the libFuzzer
 * seeds and the fixtures are built by ONE piece of code and cannot diverge.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim_blob.h"

/* Generated by ci/fuzz/extract_blob.sh from
 * ../../src/ngx_http_cache_turbo_module.c. Contains the wire constants and the
 * verbatim bodies of the deserializer functions in source order. */
#include "generated_blob.inc"

#define CT_HDR_WIRE  NGX_HTTP_CACHE_TURBO_BLOB_HDR_WIRE


/* --- failure reporting ---------------------------------------------------
 * Every assertion carries its own message. A mutation that disarms guard X must
 * produce X's message and no other; a shared "assertion failed" would let one
 * guard's red be mistaken for another's. */
static const char  *ct_ctx = "fuzz";

static void
ct_fail(const char *what)
{
    fflush(stdout);
    fprintf(stderr, "✗ [%s] %s\n", ct_ctx, what);
    fflush(stderr);
    abort();
}


/* RFC 9110 §5.6.2 tchar. A field name outside this set cannot be serialised as
 * a header line at all — nginx writes `name: value\r\n` with no escaping. */
static int
ct_is_token(const u_char *s, size_t n)
{
    size_t  i;

    if (n == 0) {
        return 0;
    }
    for (i = 0; i < n; i++) {
        u_char c = s[i];

        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
            || (c >= '0' && c <= '9'))
        {
            continue;
        }
        switch (c) {
        case '!': case '#': case '$': case '%': case '&': case '\'':
        case '*': case '+': case '-': case '.': case '^': case '_':
        case '`': case '|': case '~':
            continue;
        default:
            return 0;
        }
    }
    return 1;
}


/* CR / LF / NUL in a field value: the response-splitting primitive. */
static int
ct_value_has_ctl(const u_char *s, size_t n)
{
    size_t  i;

    for (i = 0; i < n; i++) {
        if (s[i] == '\r' || s[i] == '\n' || s[i] == '\0') {
            return 1;
        }
    }
    return 0;
}


static void
ct_in_bounds(const u_char *p, size_t plen, const u_char *buf, size_t size,
    const char *what)
{
    uintptr_t  off;

    if (p == NULL) {
        if (plen != 0) {
            ct_fail(what);
        }
        return;
    }
    if ((uintptr_t) p < (uintptr_t) buf) {
        ct_fail(what);
    }
    off = (uintptr_t) p - (uintptr_t) buf;
    if (off > (uintptr_t) size || plen > size - (size_t) off) {
        ct_fail(what);
    }
}


/*
 * Would restore_response() hand this pair to add_header()?
 *
 * With the shipped gate present this IS the production predicate. Without it,
 * production filters nothing — and neither do we, so the harness's verdict
 * tracks the code under test rather than an aspiration. See the file header.
 */
static int
ct_would_emit(ngx_http_cache_turbo_loc_conf_t *clcf,
    const u_char *nm, uint32_t nl, const u_char *vv, uint32_t vl)
{
#if CT_HAVE_HEADER_ADMISSIBLE
    return ngx_http_cache_turbo_header_admissible(clcf, (u_char *) nm, nl,
                                                  (u_char *) vv, vl) ? 1 : 0;
#else
    (void) clcf; (void) nm; (void) nl; (void) vv; (void) vl;
    return 1;
#endif
}


int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    ngx_http_cache_turbo_blob_hdr_t   hdr;
    ngx_http_cache_turbo_loc_conf_t   clcf;
    const u_char                     *hb = NULL, *body = NULL, *p, *end;
    u_char                           *buf;
    size_t                            alloc;

    /* surrogate_key off / no require_header: the widest admissible set, so the
     * harness never credits a drop to an operator opt-in. */
    memset(&clcf, 0, sizeof(clcf));

    alloc = size ? size : 1;
    buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (size) {
        memcpy(buf, data, size);
    }

    /*
     * P4-3: this input models bytes read out of L2, so it goes through the
     * SAME ingress demotion redis.c / memcached.c apply to their private
     * r->pool copy before any consumer sees the blob. Skipping this would let
     * the harness fuzz a trust level production never grants to L2 bytes --
     * and would silently stop testing the AUD-HDR1 gate the moment a fuzzed
     * blob happened to set 0x0020, because restore skips the gate on a vetted
     * blob. Clearing first is what keeps assertion (6) below live on every
     * input.
     */
    ngx_http_cache_turbo_blob_clear_vetted(buf, size);

    if (ngx_http_cache_turbo_blob_validate(buf, size, &hdr, &hb, &body,
                                           NULL, NULL, NULL, 0)
        != NGX_OK)
    {
        free(buf);
        return 0;                          /* rejected: nothing is promised */
    }

    /*
     * P4-3, the security-critical assertion of this whole change: after the
     * ingress demotion above, NO blob reaching the restore path from L2 may
     * still claim to be vetted. If this ever fires, an L2 writer has regained
     * the ability to switch off ngx_http_cache_turbo_header_admissible() by
     * setting one bit -- i.e. a one-bit response-splitting / smuggling /
     * Set-Cookie primitive, the exact AUD-HDR1 threat model. It fires if
     * clear_vetted() stops clearing, if the bit's value drifts away from what
     * clear_vetted() masks, or if a future edit reorders the demotion after
     * the parse.
     */
    if (hdr.flags & NGX_HTTP_CACHE_TURBO_BLOBF_HDRS_VETTED) {
        ct_fail("an L2-sourced blob survived ingress demotion still carrying "
                "BLOBF_HDRS_VETTED — restore would SKIP header_admissible() "
                "on attacker-controlled bytes (response splitting, smuggling, "
                "Set-Cookie)");
    }

    /* --- header-field contract the L1 fill and the serve path both inherit. */
    if (hdr.status < 100 || hdr.status > 599) {
        ct_fail("blob_validate accepted a blob whose status is outside "
                "100..599 (restore writes it to r->headers_out.status)");
    }
    if (hdr.fresh_ttl > (uint64_t) NGX_HTTP_CACHE_TURBO_TTL_MAX
        || hdr.stale_ttl > (uint64_t) NGX_HTTP_CACHE_TURBO_TTL_MAX
        || hdr.sie_ttl > (uint64_t) NGX_HTTP_CACHE_TURBO_TTL_MAX)
    {
        ct_fail("blob_validate accepted a TTL above NGX_HTTP_CACHE_TURBO_TTL_MAX");
    }
    if (hdr.stale_ttl < hdr.fresh_ttl) {
        ct_fail("blob_validate accepted stale_ttl < fresh_ttl (the store side's "
                "total-serveable-window invariant; a blob claiming a huge "
                "fresh_ttl under a normal stale_ttl is forged metadata)");
    }
    /* AUD-BLOB-CREATED: every consumer computes `now - created` as plain
     * signed time_t subtraction with no overflow check before it (module.c
     * age = ngx_time() - (time_t) bh.created, e.g. around :5344 / :6777).
     * An accepted `created` outside a plausible epoch-seconds window is
     * exactly the input that turns that subtraction into signed overflow —
     * UB — before the later `age < 0` clamp ever gets a chance to run. */
    if (hdr.created < NGX_HTTP_CACHE_TURBO_BLOB_CREATED_MIN
        || hdr.created > (int64_t) time(NULL)
                             + (int64_t) NGX_HTTP_CACHE_TURBO_FOREVER_TTL)
    {
        ct_fail("blob_validate accepted a created value outside the plausible "
                "epoch-seconds window (age = now - created is unchecked signed "
                "subtraction downstream; INT64_MIN/INT64_MAX overflow it)");
    }

    ct_in_bounds(hb, hdr.headers_len, buf, size, "header block outside the blob");
    ct_in_bounds(body, hdr.body_len, buf, size, "body outside the blob");

    /* --- the walk restore_response() itself drives. */
    p = hb;
    end = hb + hdr.headers_len;

    for (;;) {
        const u_char  *nm, *vv;
        uint32_t       nl, vl;

        if (ngx_http_cache_turbo_blob_next_header(&p, end, &nm, &nl, &vv, &vl)
            != NGX_OK)
        {
            break;
        }

        ct_in_bounds(nm, nl, buf, size, "header NAME outside the blob");
        ct_in_bounds(vv, vl, buf, size, "header VALUE outside the blob");

        if (!ct_would_emit(&clcf, nm, nl, vv, vl)) {
            continue;                      /* dropped before add_header() */
        }

        if (!ct_is_token(nm, nl)) {
            ct_fail("restore would emit a header whose NAME is not an RFC 9110 "
                    "token (add_header -> ngx_list_push, then nginx writes "
                    "\"name: value\\r\\n\" verbatim)");
        }
        if (ct_value_has_ctl(vv, vl)) {
            ct_fail("restore would emit a header VALUE containing CR, LF or NUL "
                    "(response splitting / header injection)");
        }

        /*
         * The drift assertion, and the reason AUD-HDR1 is a class rather than a
         * typo: header_skip() is the STORE side's drop list. A hostile L2 writer
         * never ran the store path, so a name on that list can only reach the
         * response via restore. Emitting one means the two directions disagree
         * about what is safe — which is the defect, independent of whether that
         * particular name happens to be token-shaped (Transfer-Encoding and
         * Set-Cookie both are).
         */
        if (ngx_http_cache_turbo_header_skip(&clcf, (u_char *) nm, nl)) {
            ct_fail("restore would emit a header the STORE side drops via "
                    "header_skip() — the two directions have drifted "
                    "(smuggling / Set-Cookie primitive)");
        }
    }

    free(buf);
    return 0;
}


/* =========================================================================
 * Deterministic fixture suite (-DCT_BLOB_FIXTURES). One fixture per AUD-HDR1
 * primitive. Each builds a blob byte-for-byte the way the store path writes it
 * (ngx_http_cache_turbo_blob_hdr_write + the CT_PUT macro), then poisons ONE
 * field, and asserts the deserializer rejects the blob or drops the header.
 * ========================================================================= */
#ifdef CT_BLOB_FIXTURES

#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

static void
ct_put_u16(u_char *p, uint16_t v)
{
    p[0] = (u_char) (v & 0xff); p[1] = (u_char) ((v >> 8) & 0xff);
}

static void
ct_put_u32(u_char *p, uint32_t v)
{
    p[0] = (u_char) (v & 0xff);        p[1] = (u_char) ((v >> 8) & 0xff);
    p[2] = (u_char) ((v >> 16) & 0xff); p[3] = (u_char) ((v >> 24) & 0xff);
}

static void
ct_put_u64(u_char *p, uint64_t v)
{
    ct_put_u32(p, (uint32_t) (v & 0xffffffffULL));
    ct_put_u32(p + 4, (uint32_t) ((v >> 32) & 0xffffffffULL));
}

typedef struct {
    const char  *name;
    const char  *value;
} ct_kv_t;

static u_char  ct_blob[8192];
static size_t  ct_blob_len;

/*
 * Build a CTB4 blob exactly as the store path does. Mirrors
 * ngx_http_cache_turbo_blob_hdr_write() + CT_PUT() in module.c; the wire
 * offsets are the ones documented on ngx_http_cache_turbo_blob_hdr_t and
 * guarded against drift by extract_blob.sh's HDR_WIRE check.
 */
static void
ct_build_created(uint32_t status, uint32_t fresh_ttl, uint32_t stale_ttl,
    uint32_t sie_ttl, uint64_t created, const ct_kv_t *kv, size_t nkv,
    const char *bodytext)
{
    u_char  *w;
    size_t   i, blen = strlen(bodytext);

    memset(ct_blob, 0, sizeof(ct_blob));

    w = ct_blob + CT_HDR_WIRE;
    for (i = 0; i < nkv; i++) {
        size_t nl = strlen(kv[i].name), vl = strlen(kv[i].value);
        ct_put_u32(w, (uint32_t) nl); w += 4;
        memcpy(w, kv[i].name, nl);    w += nl;
        ct_put_u32(w, (uint32_t) vl); w += 4;
        memcpy(w, kv[i].value, vl);   w += vl;
    }

    ct_put_u32(ct_blob + 0,  NGX_HTTP_CACHE_TURBO_BLOB_MAGIC);
    ct_put_u16(ct_blob + 4,  NGX_HTTP_CACHE_TURBO_BLOB_VERSION);
    ct_put_u16(ct_blob + 6,  0);
    ct_put_u32(ct_blob + 8,  status);
    ct_put_u32(ct_blob + 12, (uint32_t) nkv);
    ct_put_u32(ct_blob + 16, (uint32_t) ((size_t) (w - ct_blob) - CT_HDR_WIRE));
    ct_put_u32(ct_blob + 20, (uint32_t) blen);
    ct_put_u64(ct_blob + 24, created);
    ct_put_u32(ct_blob + 32, fresh_ttl);
    ct_put_u32(ct_blob + 36, stale_ttl);
    ct_put_u32(ct_blob + 40, sie_ttl);

    memcpy(w, bodytext, blen); w += blen;
    ct_blob_len = (size_t) (w - ct_blob);
}

/* Same shape as ct_build_created() but with the fixed "realistic" created
 * stamp every existing fixture uses — keeps the pre-AUD-BLOB-CREATED call
 * sites unchanged. */
static void
ct_build(uint32_t status, uint32_t fresh_ttl, uint32_t stale_ttl,
    uint32_t sie_ttl, const ct_kv_t *kv, size_t nkv, const char *bodytext)
{
    ct_build_created(status, fresh_ttl, stale_ttl, sie_ttl,
        1767225600ULL, kv, nkv, bodytext);       /* fixed created stamp */
}

/* P4-3: stamp arbitrary BLOBF_* bits onto the blob ct_build*() just produced.
 * Used to forge the one thing an L2 writer would most want to forge:
 * BLOBF_HDRS_VETTED, which claims header_admissible() has already run. The
 * fixtures below pair it with a genuinely poisoned header block, so a harness
 * (or a production ingress) that honoured the bit off the wire fails on the
 * poison rather than passing quietly. */
static void
ct_stamp_flags(uint16_t flags)
{
    ct_put_u16(ct_blob + 6, flags);
}


/* A realistic stored blob — what a warm cache_turbo entry actually looks like
 * in L2. Used as the benign fixture and as libFuzzer seed #0. */
static void
ct_build_real(void)
{
    static const ct_kv_t  kv[] = {
        { "Content-Type",  "text/html; charset=UTF-8" },
        { "ETag",          "\"6f1c-5e2a\"" },
        { "Last-Modified", "Wed, 31 Dec 2025 12:00:00 GMT" },
        { "Vary",          "Accept-Encoding" },
        { "X-Powered-By",  "PHP/8.5.0" },
    };

    ct_build(200, 60, 600, 0, kv, sizeof(kv) / sizeof(kv[0]),
             "<!doctype html><title>ok</title>");
}

/* Seed-corpus sink: when --write-corpus DIR is given every fixture blob is
 * ALSO written out as a libFuzzer seed. One builder, so the seeds and the
 * fixtures can never describe different wire layouts. */
static const char  *ct_corpus_dir;
static int          ct_seq;
static int          ct_failures;

static void
ct_run(const char *name)
{
    pid_t  pid;
    int    st;

    ct_ctx = name;
    ct_seq++;

    if (ct_corpus_dir != NULL) {
        char   path[512];
        FILE  *f;

        snprintf(path, sizeof(path), "%s/%02d_seed", ct_corpus_dir, ct_seq);
        f = fopen(path, "wb");
        if (f == NULL) {
            ct_fail("cannot open the corpus file for writing");
        }
        if (fwrite(ct_blob, 1, ct_blob_len, f) != ct_blob_len) {
            ct_fail("short write to the corpus file");
        }
        fclose(f);
        printf("  · wrote %s (%zu bytes)\n", path, ct_blob_len);
        return;                            /* seed writing only, no assertions */
    }

    /*
     * Run each fixture in a CHILD. The oracle reports by abort() (so a libFuzzer
     * find and a fixture find are the same event, with the same message), and an
     * abort would otherwise stop the suite at the first red — hiding whether the
     * remaining guards also regressed. Forking means one mutation run prints the
     * FULL picture: exactly which guards fired and which did not.
     */
    fflush(NULL);
    pid = fork();
    if (pid < 0) {
        ct_fail("fork() failed — cannot isolate the fixture");
    }
    if (pid == 0) {
        /* Every fixture goes through the SAME oracle the fuzzer uses. A fixture
         * that "passes" therefore passes the identical contract, not a weaker
         * fixture-local one. */
        LLVMFuzzerTestOneInput(ct_blob, ct_blob_len);
        _exit(0);
    }
    if (waitpid(pid, &st, 0) != pid) {
        ct_fail("waitpid() failed");
    }
    if (WIFEXITED(st) && WEXITSTATUS(st) == 0) {
        printf("  ✓ %s\n", name);
    } else {
        printf("  ✗ %s\n", name);
        ct_failures++;
    }
    fflush(stdout);
}

int
main(int argc, char **argv)
{
    static const ct_kv_t  kv_crlf[] = {
        { "Content-Type", "text/html" },
        { "X-Injected",   "ok\r\nSet-Cookie: sid=attacker" },
    };
    static const ct_kv_t  kv_te[] = {
        { "Content-Type",      "text/html" },
        { "Transfer-Encoding", "chunked" },
    };
    static const ct_kv_t  kv_cookie[] = {
        { "Content-Type", "text/html" },
        { "Set-Cookie",   "sid=attacker; Path=/" },
    };
    static const ct_kv_t  kv_badname[] = {
        { "Content-Type",   "text/html" },
        { "X-Bad\r\nEvil:", "1" },
    };

    if (argc == 3 && strcmp(argv[1], "--write-corpus") == 0) {
        ct_corpus_dir = argv[2];
    }

    printf("--- L2 blob deserializer fixtures (AUD-HDR1 / AUD-FUZZ1) ---\n");
#if !CT_HAVE_HEADER_ADMISSIBLE
    printf("  ⚠ header_admissible() is ABSENT from the shipped source — these "
           "fixtures model an UNFILTERED restore and are expected to abort.\n");
#endif

    /* 0. the benign, realistic blob: must pass every assertion untouched.
     *    Without this a fix that rejected EVERYTHING would look green. */
    ct_build_real();
    ct_run("real stored blob (200, 5 headers, body) survives");

    /* 1. CR/LF in a value -> response splitting. */
    ct_build(200, 60, 600, 0, kv_crlf, 2, "body");
    ct_run("CRLF in a header value is dropped");

    /* 2. Transfer-Encoding -> request smuggling vs a downstream proxy/CDN.
     *    It is on the STORE skip list; restore must mirror that. */
    ct_build(200, 60, 600, 0, kv_te, 2, "body");
    ct_run("Transfer-Encoding is dropped on restore");

    /* 3. Set-Cookie -> session fixation. Also store-skipped. */
    ct_build(200, 60, 600, 0, kv_cookie, 2, "body");
    ct_run("Set-Cookie is dropped on restore");

    /* 4. a non-token header NAME containing its own CRLF. */
    ct_build(200, 60, 600, 0, kv_badname, 2, "body");
    ct_run("non-token header name is dropped");

    /*
     * 4a-4d (P4-3). THE security-critical fixtures for BLOBF_HDRS_VETTED.
     *
     * The bit tells restore_response_headers() "header_admissible() already
     * ran over this block, skip it". That is true only of a blob this worker
     * serialised. Because the store path writes the SAME buffer to L1 and to
     * L2 (filters.c backend->set), a stamped blob genuinely does reach Redis
     * / memcached -- so an L2 writer can hand it straight back, or simply set
     * the bit themselves on a blob of their own. If that bit survived
     * ingress, one bit would disable the entire AUD-HDR1 gate on
     * attacker-controlled bytes.
     *
     * Each fixture re-runs a poison from above with 0x0020 forged on top. The
     * assertion that catches it is the demotion check in
     * LLVMFuzzerTestOneInput(): the harness clears the bit exactly as
     * redis.c/memcached.c do, then requires it to be gone. If clear_vetted()
     * stops clearing, or the bit drifts from what it masks, every one of
     * these goes red -- AND so does the underlying poison assertion, because
     * a vetted blob would take the skip path. Two independent reds, which is
     * the point: neither can mask the other into silence.
     */
    ct_build(200, 60, 600, 0, kv_crlf, 2, "body");
    ct_stamp_flags(NGX_HTTP_CACHE_TURBO_BLOBF_HDRS_VETTED);
    ct_run("forged HDRS_VETTED does not smuggle a CRLF value past the gate");

    ct_build(200, 60, 600, 0, kv_te, 2, "body");
    ct_stamp_flags(NGX_HTTP_CACHE_TURBO_BLOBF_HDRS_VETTED);
    ct_run("forged HDRS_VETTED does not smuggle Transfer-Encoding");

    ct_build(200, 60, 600, 0, kv_cookie, 2, "body");
    ct_stamp_flags(NGX_HTTP_CACHE_TURBO_BLOBF_HDRS_VETTED);
    ct_run("forged HDRS_VETTED does not smuggle Set-Cookie");

    /* 4d: the bit forged on an OTHERWISE CLEAN blob. Negative control for the
     * three above -- it proves the demotion assertion fires on the BIT alone,
     * not merely as a side effect of the poisoned header. Without this, a
     * clear_vetted() that had been deleted entirely would still look caught,
     * because the poison assertions alone would explain every red. */
    ct_build_real();
    ct_stamp_flags(NGX_HTTP_CACHE_TURBO_BLOBF_HDRS_VETTED);
    ct_run("forged HDRS_VETTED on a clean blob is stripped at ingress");

    /* 5. status = 0xFFFFFFFF -> written straight to headers_out.status. */
    ct_build(0xFFFFFFFFu, 60, 600, 0, kv_crlf + 0, 1, "body");
    ct_run("status=0xFFFFFFFF is rejected");

    /* 6. fresh_ttl = 0xFFFFFFFF (~136 years) under a normal stale window ->
     *    permanent poison. TTL_MAX is itself 0xFFFFFFFF, so a bare
     *    "clamp to TTL_MAX" would be VACUOUS here — the invariant that
     *    actually bites is stale_ttl >= fresh_ttl, which the store path
     *    always satisfies and a forged blob does not. */
    ct_build(200, 0xFFFFFFFFu, 600, 0, kv_crlf + 0, 1, "body");
    ct_run("fresh_ttl=0xFFFFFFFF under a normal stale_ttl is rejected");

    /* 7. created = INT64_MIN (AUD-BLOB-CREATED). Every consumer computes
     *    `now - created` as plain signed time_t subtraction with no overflow
     *    check before it — INT64_MIN there is signed overflow (UB) before the
     *    later `age < 0` clamps ever run. A hostile or corrupt L2 blob can
     *    carry this; the deserializer must reject it outright. */
    ct_build_created(200, 60, 600, 0, (uint64_t) INT64_MIN,
        kv_crlf + 0, 1, "body");
    ct_run("created=INT64_MIN is rejected");

    /* 8. created = INT64_MAX: symmetric far-future forgery. Also poisons
     *    `now - created` (a huge negative age) and claims a store time no
     *    real node clock could produce. */
    ct_build_created(200, 60, 600, 0, (uint64_t) INT64_MAX,
        kv_crlf + 0, 1, "body");
    ct_run("created=INT64_MAX is rejected");

    if (ct_failures) {
        printf("--- %d of %d blob fixtures FAILED ---\n", ct_failures, ct_seq);
        return 1;
    }
    printf("--- all blob fixtures passed ---\n");
    return 0;
}

#endif /* CT_BLOB_FIXTURES */
