/*
 * libFuzzer harness for ngx_http_cache_turbo_normalized_args_variable().
 *
 * Why this target: it builds $cache_turbo_normalized_args from the FULLY
 * attacker-controlled query string (r->args). It splits on '&'/'=' with
 * ngx_strlchr pointer arithmetic, drops denied params, stable-sorts what
 * remains, computes a buffer size `total`, allocates it, and writes a
 * '?'-prefixed result. Two bug classes live here and the runtime suite
 * misses both:
 *   - OOB-read while splitting (amp/eq walks over r->args.data .. +len)
 *   - OOB-write if `total` ever under-counts what the build loop writes
 * The harness feeds the raw query bytes as r->args with NO trailing NUL
 * (exact-sized allocation) so ASAN flags any read at/over args.len, and
 * UBSAN+ASAN catch any miscount in the build buffer.
 *
 * The body is sliced VERBATIM from src/ngx_http_cache_turbo_module.c by
 * extract_norm_args.sh into generated_norm_args.inc (no copy drift).
 * ngx_shim_args.h supplies the reduced nginx surface and stubs the three
 * helpers whose behaviour does not affect the size-vs-write bound (see
 * that header).
 *
 * Build (see ci/fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_norm_args.c -o fuzz_norm_args
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim_args.h"

/* Definition of the loc-conf the sliced handler fetches via the macro. */
ngx_http_cache_turbo_loc_conf_t *g_fuzz_clcf;

/* Generated by ci/fuzz/extract_norm_args.sh — verbatim tok_cmp() +
 * normalized_args_variable(). */
#include "generated_norm_args.inc"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * The whole input is the query string. normalize_vary is held at 0 so the
     * Vary-suffix path (which needs the live request) stays out — the attacker
     * surface here is the arg splitter + buffer builder. The "emit suffix only"
     * early path is reached on an empty input (r->args.len == 0).
     */
    ngx_http_cache_turbo_loc_conf_t clcf;
    clcf.normalize_vary      = 0;
    clcf.normalize_strip     = NGX_CONF_UNSET_PTR;
    g_fuzz_clcf = &clcf;

    /*
     * R3-1: the arg cap (cache_turbo_normalize_max_args) added a SECOND exit
     * from this function -- above the cap it skips the sort/strip entirely and
     * keys the raw arg string through a different allocation and copy. Pinning
     * the cap to one value would leave one of those two buffer builders
     * unfuzzed, which is precisely the half a length-driven input is best at
     * breaking. So the first input byte selects the regime, and the rest is the
     * query string:
     *   low bit clear -> 0, unlimited: always normalize (pre-R3-1 behaviour)
     *   low bit set   -> a small cap (1..8), so ordinary inputs go OVER it and
     *                    take the raw-args path
     * The selector byte is consumed, not left in the query string, so a corpus
     * entry means the same thing on every run.
     */
    uint8_t regime = 0;
    if (size > 0) {
        regime = data[0];
        data++;
        size--;
    }
    clcf.normalize_max_args = (regime & 1) ? (ngx_int_t) ((regime >> 1) % 8 + 1)
                                           : 0;

    const uint8_t *args = (size > 0) ? data : NULL;
    size_t         alen = size;

    /* Exact-sized, non-NUL-terminated args buffer (>=1 byte, never NULL:
     * r->args.data is always a real buffer in production). */
    size_t  cap = alen ? alen : 1;
    u_char *buf = (u_char *) malloc(cap);
    if (buf == NULL) {
        return 0;
    }
    if (alen) {
        memcpy(buf, args, alen);
    }

    ngx_pool_t pool = { {0}, 0 };

    ngx_http_request_t r;
    r.args.data = buf;
    r.args.len  = alen;
    r.pool      = &pool;

    ngx_http_variable_value_t v;
    memset(&v, 0, sizeof(v));

    ngx_int_t rc = ngx_http_cache_turbo_normalized_args_variable(&r, &v, 0);

    if (rc != NGX_OK && rc != NGX_ERROR) {
        __builtin_trap();
    }

    /* On success the output must be self-consistent: a non-empty result
     * starts with '?' and v->data/len must be readable in full (touch it
     * so ASAN validates the whole range the handler claims it wrote). */
    if (rc == NGX_OK && v.len > 0) {
        if (v.data[0] != '?') {
            __builtin_trap();
        }
        volatile uint8_t sink = 0;
        for (unsigned i = 0; i < v.len; i++) {
            sink ^= v.data[i];
        }
        (void) sink;
    }

    ngx_fuzz_pool_reset(&pool);
    free(buf);
    return 0;
}
