/*
 * libFuzzer harness for the cache-turbo memcached GET reply parser (v13):
 *   ngx_http_cache_turbo_mc_parse()  - VALUE <key> <flags> <bytes>[ <cas>] ...
 *
 * Why this target: the parser reads a memcached reply — attacker-influenceable
 * bytes from a shared, possibly buggy or compromised L2 — doing header-line
 * scanning and <bytes>-length pointer arithmetic against op->rbuf .. op->rbuf +
 * op->rlen. A single off-by-one in a space/CRLF scan or a length check is a
 * worker-crashing OOB read. The parser is fully length-bounded (no NUL
 * reliance), so this harness feeds a buffer sized EXACTLY to op->rlen with NO
 * trailing NUL: ASAN then turns any read at or past the end — any reintroduced
 * NUL-bounded scan or off-by-one — into an immediate, reproducible
 * heap-buffer-overflow.
 *
 * The real parser body lives in ../src/ngx_http_cache_turbo_memcached.c;
 * fuzz/extract_mc_parser.sh slices just that one function into
 * generated_mc_parser.inc at build time, so we always fuzz the SHIPPED code with
 * no copy drift. ngx_shim_mc.h supplies the tiny nginx surface it needs.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_mc_parser.c -o fuzz_mc_parser
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim_mc.h"

/* Generated by fuzz/extract_mc_parser.sh from
 * ../src/ngx_http_cache_turbo_memcached.c. Contains the verbatim body of the
 * memcached GET reply parser. */
#include "generated_mc_parser.inc"

/* Validate that an ngx_str_t the parser handed back references INTO the input
 * buffer (or is the NULL nil sentinel), never outside it. A parser that returns
 * NGX_OK with a blob pointing past the buffer is a bug ASAN would not otherwise
 * see (the read happens later, in the caller). */
static void
check_in_bounds(const u_char *blob, size_t blob_len,
    const u_char *buf, size_t size)
{
    if (blob == NULL) {
        if (blob_len != 0) {
            __builtin_trap();              /* NULL data with nonzero len */
        }
        return;
    }
    if (blob < buf || blob + blob_len < blob /* overflow */
        || blob + blob_len > buf + size)
    {
        __builtin_trap();                  /* points outside the input buffer */
    }
}

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    ngx_http_cache_turbo_mc_op_t  op;
    u_char    *buf;
    u_char    *blob = NULL;
    size_t     blob_len = 0;
    size_t     alloc;
    ngx_int_t  rc;

    /*
     * Allocate EXACTLY `size` bytes (one byte when size == 0, since malloc(0)
     * is implementation-defined) and do NOT NUL-terminate: any read at or past
     * op->rlen becomes an ASAN heap-buffer-overflow.
     */
    alloc = size ? size : 1;
    buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (size) {
        memcpy(buf, data, size);
    }

    op.rbuf = buf;
    op.rlen = size;

    rc = ngx_http_cache_turbo_mc_parse(&op, &blob, &blob_len);
    if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED) {
        __builtin_trap();                  /* undocumented return */
    }
    if (rc == NGX_OK) {
        check_in_bounds(blob, blob_len, buf, size);
    }

    free(buf);
    return 0;
}
