/*
 * libFuzzer harness for the cache-turbo RESP reply parsers:
 *   ngx_http_cache_turbo_redis_parse()        - bulk-string GET reply
 *   ngx_http_cache_turbo_redis_parse_array()  - SMEMBERS array reply
 *   ngx_http_cache_turbo_redis_parse_scan()   - SCAN [cursor, keys] 2-tuple
 *
 * Why this target: these functions parse a Redis reply — attacker-influenceable
 * bytes from a shared, possibly buggy or compromised L2 — doing length-line and
 * bulk-string pointer arithmetic against op->rbuf .. op->rbuf + op->rlen. A
 * single off-by-one in a CRLF scan or a length check is a worker-crashing OOB
 * read. The parsers are fully length-bounded (no NUL reliance), so this harness
 * feeds a buffer sized EXACTLY to op->rlen with NO trailing NUL: ASAN then turns
 * any read at or past the end — i.e. any reintroduced NUL-bounded scan or
 * off-by-one — into an immediate, reproducible heap-buffer-overflow.
 *
 * The real parser bodies live in ../src/ngx_http_cache_turbo_redis.c and depend
 * on the nginx tree; fuzz/extract_parser.sh slices just those three functions
 * into generated_parser.inc at build time, so we always fuzz the SHIPPED code
 * with no copy drift. ngx_shim.h supplies the tiny nginx surface they need
 * (op struct, pool, ngx_atoi/ngx_strlchr) with faithful upstream semantics.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_resp_parser.c -o fuzz_resp_parser
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh from
 * ../src/ngx_http_cache_turbo_redis.c. Contains the verbatim bodies of the
 * three RESP parsers in source order. */
#include "generated_parser.inc"

/* Validate that an ngx_str_t the parser handed back references INTO the input
 * buffer (or is the empty/NULL nil sentinel), never outside it. A parser that
 * returns NGX_OK with a member pointing past the buffer is a bug ASAN would not
 * otherwise see (the read happens later, in the caller). */
static void
check_in_bounds(const u_char *blob, size_t blob_len,
    const u_char *buf, size_t size)
{
    uintptr_t  blob_addr, buf_addr, offset;

    if (blob == NULL) {
        if (blob_len != 0) {
            __builtin_trap();              /* NULL data with nonzero len */
        }
        return;
    }
    blob_addr = (uintptr_t) blob;
    buf_addr = (uintptr_t) buf;
    if (blob_addr < buf_addr) {
        __builtin_trap();
    }
    offset = blob_addr - buf_addr;
    if (offset > (uintptr_t) size
        || blob_len > size - (size_t) offset)
    {
        __builtin_trap();                  /* points outside the input buffer */
    }
}

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    ngx_pool_t  pool;
    u_char     *buf;
    size_t      alloc;

    pool.nallocs = 0;

    /*
     * Allocate EXACTLY `size` bytes (one byte when size == 0, since malloc(0)
     * is implementation-defined) and do NOT NUL-terminate: any read at or past
     * ae->len / op->rlen becomes an ASAN heap-buffer-overflow.
     */
    alloc = size ? size : 1;
    buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }
    if (size) {
        memcpy(buf, data, size);
    }

    /* 1) GET bulk-string parser. */
    {
        ngx_http_cache_turbo_redis_op_t  op;
        u_char    *blob = NULL;
        size_t     blob_len = 0;
        ngx_int_t  rc;

        op.rbuf = buf;
        op.rlen = size;
        op.pool = &pool;

        rc = ngx_http_cache_turbo_redis_parse(&op, &blob, &blob_len);
        /* L13-fix: this parser is TRI-state on failure. NGX_DECLINED is now
         * reserved for a well-formed `$-1` nil (a DEFINITIVE miss, the only
         * outcome allowed to arm the L13 negative memo) and NGX_ERROR covers
         * every not-an-answer reply: a Redis error reply, an unexpected type
         * byte, an unparseable length, an oversized payload. Both are legal
         * returns; conflating them is the bug the split exists to prevent. */
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED
            && rc != NGX_ERROR)
        {
            __builtin_trap();              /* undocumented return */
        }
        if (rc == NGX_OK) {
            check_in_bounds(blob, blob_len, buf, size);
        }
        /* A failure return must never hand back a blob. */
        if (rc != NGX_OK && (blob != NULL || blob_len != 0)) {
            __builtin_trap();
        }
        ngx_fuzz_pool_reset(&pool);
    }

    /* 2) SMEMBERS array parser. */
    {
        ngx_http_cache_turbo_redis_op_t  op;
        ngx_str_t  *members = NULL;
        ngx_uint_t  nmembers = 0;
        ngx_int_t   rc;

        op.rbuf = buf;
        op.rlen = size;
        op.pool = &pool;

        rc = ngx_http_cache_turbo_redis_parse_array(&op, &members, &nmembers);
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED) {
            __builtin_trap();
        }
        if (rc == NGX_OK) {
            for (ngx_uint_t i = 0; i < nmembers; i++) {
                check_in_bounds(members[i].data, members[i].len, buf, size);
            }
        }
        ngx_fuzz_pool_reset(&pool);
    }

    /* 3) SCAN 2-tuple parser. */
    {
        ngx_http_cache_turbo_redis_op_t  op;
        ngx_str_t   cursor = { 0, NULL };
        ngx_str_t  *keys = NULL;
        ngx_uint_t  nkeys = 0;
        ngx_int_t   rc;

        op.rbuf = buf;
        op.rlen = size;
        op.pool = &pool;

        rc = ngx_http_cache_turbo_redis_parse_scan(&op, &cursor, &keys, &nkeys);
        if (rc != NGX_OK && rc != NGX_AGAIN && rc != NGX_DECLINED) {
            __builtin_trap();
        }
        if (rc == NGX_OK) {
            check_in_bounds(cursor.data, cursor.len, buf, size);
            for (ngx_uint_t i = 0; i < nkeys; i++) {
                check_in_bounds(keys[i].data, keys[i].len, buf, size);
            }
        }
        ngx_fuzz_pool_reset(&pool);
    }

    free(buf);
    return 0;
}
