#!/usr/bin/env bash
# ci/linter/lint-astgrep.sh -- ast-grep structural sink sweep over src/*.[ch].
#
# Structural, not textual. The other C checkers here read the file as tokens
# (flawfinder's risky-API list) or as a whole translation unit (cppcheck,
# clang-tidy); ast-grep reads it as a PARSE TREE, so a rule can say "memcpy
# whose third argument is a sizeof of a pointer" and mean it -- a shape grep
# cannot express and a TU-level analyzer will not report unless it can also
# prove the overflow. That is the gap this fills: cheap, shape-level sinks,
# checked on every commit rather than in the nightly deep lane.
#
# Ruleset is ci/ast-grep/: rules/own/ (this superrepo's C and nginx rules) plus
# rules/vendor/ (the C/C++ slice of CodeRabbit's Apache-2.0 `essentials` pack,
# CWE-tagged -- the rules the bot itself runs on a pull request, so a hit here
# is a review comment caught before the push). Both are GENERATED by
# tools/vendor-astgrep-rules.py; refresh with that script, never by hand.
#
#   -c ci/ast-grep/sgconfig.yml is LOAD-BEARING, do not drop it to let ast-grep
#       "find the config itself". ast-grep resolves sgconfig.yml by walking UP
#       from the working directory. Without -c, this checker binds to
#       /opt/myguard/sgconfig.yml while the clone sits inside the superrepo,
#       and binds to NOTHING in a standalone clone -- scanning against an empty
#       ruleset and reporting green. The rules are vendored into ci/ast-grep/
#       precisely so this gate is self-contained wherever the clone lives.
#
# THE GATE IS THE PROMOTED LIST, NOT THE RULESET. ast-grep has no severity
# threshold flag (unlike `semgrep --severity`) and exits non-zero only on
# `error`, so the gate is built by PROMOTING named rules with --error=;
# everything else stays advisory -- printed, never blocking.
#
# That split is what makes this gateable at all. Measured across every module
# repo 2026-08-08: 318 of 368 findings are note[nginx-unchecked-palloc], which
# in nginx C is frequently legitimate (call sites propagate NULL deliberately).
# Gating the note tier would land every repo red on arrival and train everyone
# to --no-verify -- the same failure mode the shellcheck note in lint-sh.sh
# describes. A rule joins PROMOTED only after its findings are measured on real
# trees and confirmed real.
#
# Keep PROMOTED identical to the --error= list in .pre-commit-config.yaml's
# ast-grep hook. Two gates disagreeing about what blocks is worse than one:
# the hook passes, CI fails, and the difference is invisible in both outputs.
#
# A PROMOTED NAME THAT DOES NOT EXIST IS SILENTLY IGNORED. Verified against
# ast-grep 0.44.1 on 2026-08-10: `--error=no-such-rule-xyz` exits 0 without a
# word of complaint, so a typo (or a rule renamed by a ruleset refresh) does not
# fail loudly -- it quietly un-gates that rule and the checker keeps reporting
# green. Nothing in ast-grep catches this, which is why every name in PROMOTED
# is checked against the ruleset below BEFORE the scan runs. Do not drop that
# check on the grounds that ast-grep "would surely error": it does not.
#
# Usage: ci/linter/lint-astgrep.sh [files...]   Env: LINT_MODE=staged|all
# Exit:  0 clean, 1 a promoted rule fired, 2 ast-grep missing, config gone, or
#        a PROMOTED name that no rule defines.
# Extend: add rules via tools/vendor-astgrep-rules.py. Promote one by adding it
# to PROMOTED here AND to the pre-commit hook, once its findings are confirmed.

# shellcheck source=ci/linter/lib.sh
. "$(git rev-parse --show-toplevel)/ci/linter/lib.sh"

# Rules whose findings are confirmed real and therefore BLOCK. Everything else
# in the ruleset still runs and still prints, at its own severity.
#
# RE-MEASURED for this module (adoption step 32), 2026-08-10, against the 35
# vendored rules over src/ (17 .c / 11 .h). Promotion is a measurement here,
# not a copy of the skeleton's list -- the skeleton promotes six rules because
# they were confirmed on ITS trees.
#
# Full finding distribution on this repo:
#     80  info     nginx-unchecked-palloc   (advisory, as in every module repo)
#      9  warning  c-alloc-mul-overflow     (all nine legitimate -- see below)
#      0           everything else
#
# c-alloc-mul-overflow is NOT promoted, and that is the one deliberate
# divergence from the skeleton. All nine hits are `count * sizeof(T)` where the
# count cannot reach overflow:
#   redis.c:2367,2563   count capped by REDIS_MAX_MEMBERS before the alloc
#   module.c:12017      n bounded by r->args.len ('&' count + 1)
#   module.c:10485      nmembers from the capped member list above
#   redis.c:1164,1168   REDIS_DEL_CHUNK is a compile-time constant
#   redis.c:346         max = clcf->redis_keepalive, a config directive
#   memcached.c:148     max = clcf->memcached_keepalive, a config directive
# Promoting it would land this repo red on arrival on nine non-bugs, which is
# how a gate trains everyone to --no-verify. It stays advisory: printed on
# every run, blocking nothing, and a TENTH hit is visible for triage.
#
# The other five stay promoted: each is defined by the ruleset (the check below
# proves that) and each currently has zero findings here, so promoting them
# gates future regressions at no cost today.
PROMOTED=(
    c-memcpy-sizeof-pointer
    c-sizeof-wrong-operand
    c-unbounded-string-copy
    c-format-string
    c-shell-exec
)

lint_files_into FILES '^src/.*\.[ch]$' "$@"
[ "${#FILES[@]}" -gt 0 ] || { echo "lint-astgrep: no C files to check"; exit 0; }

echo "lint-astgrep: ${#FILES[@]} file(s)"

need ast-grep "see ci/linter/install-linters.sh (pinned upstream binary)"

CONFIG="ci/ast-grep/sgconfig.yml"
# A missing config is exit 2 ("could not run"), never a clean pass. Without
# this, a deleted or unported ci/ast-grep/ makes ast-grep scan an empty ruleset
# and exit 0 -- the exact green-while-checking-nothing failure the -c flag
# exists to prevent.
[ -f "$CONFIG" ] || die "$CONFIG missing -- regenerate with tools/vendor-astgrep-rules.py"

# Every promoted name must actually be defined by a rule, or the promotion is a
# no-op that reads as a gate (see the header note). Rule ids are the `id:` field
# of the vendored YAML; the ruleset is generated, so this stays a plain scan of
# ci/ast-grep/rules/ rather than anything that needs ast-grep to cooperate.
# Capture before loading: mapfile over process substitution would discard a
# traversal/read failure after grep had already emitted plausible rule ids.
if known_lines="$(grep -rhE '^id:[[:space:]]*' ci/ast-grep/rules/ \
                   | sed -E 's/^id:[[:space:]]*//; s/[[:space:]]*$//' \
                   | sort -u)"; then
    :
else
    die "could not read rule ids under ci/ast-grep/rules/"
fi
KNOWN=()
if [ -n "$known_lines" ]; then
    mapfile -t KNOWN <<< "$known_lines"
fi
[ "${#KNOWN[@]}" -gt 0 ] || die "no rule ids under ci/ast-grep/rules/ -- ruleset empty or unported"

# Membership is tested in-process, NOT via `printf ... | grep -qx`.
#
# `grep -q` exits on its FIRST match and closes the read end. The printf
# builtin can still be mid-write, and on some bash builds that write fails with
# EPIPE, printing "printf: write error: Broken pipe" AND returning non-zero for
# the pipeline -- whereupon the `||` reads a successful match as "no match" and
# condemns a rule that plainly exists.
#
# Observed 2026-08-14: `Lint / Linters` red with
#   line 121: printf: write error: Broken pipe
#   ERROR: PROMOTED names no rule defines: c-format-string
# while c-format-string.yml has been present and correctly `id:`-tagged since
# d085d68. It reproduced ONLY on the runner -- the same SHA went green on one
# dispatch run and red on another, and never locally -- because whether the
# write races the close depends on bash version and scheduling, not on source.
# A verdict that flips on pipe timing is not a verdict, so the pipe is gone:
# the loop below cannot fail this way on any shell.
unknown=""
for r in "${PROMOTED[@]}"; do
    found=""
    for k in "${KNOWN[@]}"; do
        [ "$k" = "$r" ] && { found=1; break; }
    done
    [ -n "$found" ] || unknown="$unknown $r"
done
[ -z "$unknown" ] || die "PROMOTED names no rule defines:$unknown
       | ast-grep ignores an unknown --error= silently, so these gate NOTHING.
       | Fix the spelling or drop them; keep .pre-commit-config.yaml in step."

ERRFLAGS=()
for r in "${PROMOTED[@]}"; do ERRFLAGS+=("--error=$r"); done

say "ast-grep (${#PROMOTED[@]} promoted rule(s) block; rest advisory)"
ast-grep scan -c "$CONFIG" "${ERRFLAGS[@]}" "${FILES[@]}"
rc=$?

# 0 clean, 1 a promoted rule fired. Anything else is ast-grep failing to run
# (6 = config error, verified 2026-08-10), which is "could not run", not clean.
case "$rc" in
    0|1) exit "$rc" ;;
    *)   die "ast-grep exited $rc -- could not run (config error?), not a verdict" ;;
esac
